import NextAuth from 'next-auth'
import Google from 'next-auth/providers/google'

import { isTokenExpired, refreshAccessToken, RefreshTokenError } from './auth/refresh-token'
import { log } from './logger'

/**
 * Auth.js v5 configuration for IAra.
 *
 * Provides Google OAuth authentication with YouTube API access.
 * Exports auth(), signIn(), signOut(), and handlers for use throughout the app.
 *
 * YouTube OAuth scopes:
 * - youtube.readonly: Read videos, playlists, channel info
 * - youtube.force-ssl: Update video metadata (title, description, tags)
 *
 * Note: youtube.upload scope does NOT exist. Use youtube.force-ssl for updates.
 *
 * @see https://authjs.dev/getting-started/installation?framework=next.js
 */

/** YouTube OAuth scopes required for IAra functionality */
export const YOUTUBE_SCOPES = [
  'https://www.googleapis.com/auth/youtube.readonly',
  'https://www.googleapis.com/auth/youtube.force-ssl',
  // Epic 30 (mediakit): horas assistidas + série diária via Analytics API.
  // Adicionado em 2026-08-31 (decisão A3) — exige re-login para valer.
  'https://www.googleapis.com/auth/yt-analytics.readonly',
].join(' ')

export const { handlers, signIn, signOut, auth } = NextAuth({
  providers: [
    Google({
      clientId: process.env.AUTH_GOOGLE_ID!,
      clientSecret: process.env.AUTH_GOOGLE_SECRET!,
      authorization: {
        params: {
          scope: `openid email profile ${YOUTUBE_SCOPES}`,
          access_type: 'offline',
          prompt: 'consent',
          // CRITICAL: prompt: 'consent' is REQUIRED to guarantee refresh_token.
          // Without it, Google only returns refresh_token on first-ever authorization.
          // If user revokes and re-authorizes, no refresh_token is returned without prompt.
          // Trade-off: User sees consent screen on every login (acceptable for admin tool).
          // See: https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient
        },
      },
    }),
  ],
  pages: {
    signIn: '/login',
    error: '/auth/error',
  },
  callbacks: {
    async jwt({ token, account }) {
      // Initial sign in - capture all tokens
      if (account) {
        token.accessToken = account.access_token
        token.expiresAt = account.expires_at

        // CRITICAL: Use providerAccountId (Google User ID) as the stable user identifier
        // token.sub is a UUID generated by Auth.js that changes each session without a DB adapter
        // providerAccountId is the Google User ID (e.g., "117853...") which is immutable
        const userId = account.providerAccountId as string
        token.userId = userId

        // CRITICAL: Only save refresh_token if it comes (first authorization only)
        // Google only sends refresh_token on first consent, never overwrite existing
        if (account.refresh_token) {
          token.refreshToken = account.refresh_token
          log('INFO', 'Refresh token captured', { userId })
        } else if (!token.refreshToken) {
          // No refresh token from Google and none saved - this is a problem
          log('WARN', 'No refresh token available', {
            userId,
            hasExistingToken: !!token.refreshToken,
          })
        }

        // Persist user document and tokens to Firestore
        try {
          // Save/update podcast-scoped user document (upsert - prevents duplicates)
          const { createOrUpdateUserOnLogin } = await import('./firebase/users-admin')
          const { PODCAST_ID } = await import('./firebase/config')
          const user = await createOrUpdateUserOnLogin(PODCAST_ID, {
            oderId: userId,
            email: token.email as string,
            displayName: token.name as string | null,
            photoURL: token.picture as string | null,
          })

          // Store user role in JWT for fast access
          token.role = user.role

          // Save tokens to subcollection
          const { saveUserTokens } = await import('./firebase/tokens')
          await saveUserTokens(userId, {
            accessToken: account.access_token as string,
            refreshToken: account.refresh_token as string | undefined,
            expiresAt: account.expires_at as number | undefined,
          })
        } catch (error) {
          log('ERROR', 'Failed to save user data to Firestore', {
            userId,
            error: error instanceof Error ? error.message : 'Unknown error',
          })
        }

        log('INFO', 'User signed in with YouTube scopes', {
          userId,
          provider: account.provider,
          hasAccessToken: !!account.access_token,
          hasRefreshToken: !!account.refresh_token,
          expiresAt: account.expires_at,
        })

        return token
      }

      // Existing session - check if token needs refresh
      const userId = token.userId as string | undefined

      if (!isTokenExpired(token.expiresAt as number | undefined)) {
        // Token is still valid
        return token
      }

      // Token expired or expiring soon - attempt refresh
      log('INFO', 'Token expiring, attempting refresh', {
        userId,
        expiresAt: token.expiresAt,
      })

      if (!token.refreshToken) {
        log('ERROR', 'Cannot refresh token - no refresh_token available', {
          userId,
        })
        return { ...token, error: 'RefreshAccessTokenError' as const }
      }

      try {
        const refreshed = await refreshAccessToken(token.refreshToken as string)

        // Persist refreshed tokens to Firestore
        if (userId) {
          try {
            const { saveUserTokens } = await import('./firebase/tokens')
            await saveUserTokens(userId, {
              accessToken: refreshed.accessToken,
              expiresAt: refreshed.expiresAt,
              // Note: refresh_token is NOT returned in refresh response, keep existing
            })
          } catch (saveError) {
            log('ERROR', 'Failed to persist refreshed tokens', {
              userId,
              error: saveError instanceof Error ? saveError.message : 'Unknown error',
            })
            // Continue anyway - token is refreshed in memory
          }
        }

        log('INFO', 'Token refresh successful', {
          userId,
          newExpiresAt: refreshed.expiresAt,
        })

        return {
          ...token,
          accessToken: refreshed.accessToken,
          expiresAt: refreshed.expiresAt,
          error: undefined, // Clear any previous error
        }
      } catch (error) {
        log('ERROR', 'Token refresh failed', {
          userId,
          error: error instanceof Error ? error.message : 'Unknown error',
          isInvalidGrant: error instanceof RefreshTokenError && error.code === 'INVALID_GRANT',
        })

        // Return token with error flag for session callback to handle
        return { ...token, error: 'RefreshAccessTokenError' as const }
      }
    },
    async session({ session, token }) {
      const userId = token.userId as string | undefined

      // Handle refresh token error - force re-authentication
      if (token.error === 'RefreshAccessTokenError') {
        log('WARN', 'Session invalidated due to refresh token error', {
          userId,
        })
        // Return session with error flag for client-side handling
        // Client should check session.error and redirect to login
        return {
          ...session,
          user: session.user,
          error: 'RefreshAccessTokenError' as const,
        }
      }

      // Validate user exists in Firestore
      // This prevents stale JWT sessions from accessing the app after user deletion
      if (userId) {
        try {
          const { getUser } = await import('./firebase/users')
          const user = await getUser(userId)

          if (!user) {
            log('WARN', 'Session invalidated - user not found in Firestore', {
              userId,
            })
            return {
              ...session,
              user: session.user,
              error: 'UserNotFoundError' as const,
            }
          }

          // Add user id and role to session (using stable Google User ID)
          session.user.id = userId
          session.user.role = user.role
        } catch (error) {
          log('ERROR', 'Failed to validate user in Firestore', {
            userId,
            error: error instanceof Error ? error.message : 'Unknown error',
          })
          // On error, allow session to continue but log for monitoring
          // This prevents Firestore outages from blocking all users
          session.user.id = userId
          // Use role from JWT token as fallback
          session.user.role = (token.role as 'admin' | 'user') ?? 'user'
        }
      }

      return session
    },
    async redirect({ url, baseUrl }) {
      // Allow relative callback URLs
      if (url.startsWith('/')) return `${baseUrl}${url}`
      // Allow callback URLs on the same origin
      if (new URL(url).origin === baseUrl) return url
      return baseUrl
    },
  },
  events: {
    async signOut() {
      log('INFO', 'User signed out')
    },
  },
  debug: process.env.NODE_ENV === 'development',
})

// Extend the Session type to include user.id, role and error types
declare module 'next-auth' {
  interface Session {
    user: {
      id: string
      name?: string | null
      email?: string | null
      image?: string | null
      role: 'admin' | 'user' // User role for authorization
    }
    error?: 'RefreshAccessTokenError' | 'UserNotFoundError'
  }

  interface JWT {
    accessToken?: string
    refreshToken?: string
    expiresAt?: number
    userId?: string // Google User ID (providerAccountId) - stable across sessions
    role?: 'admin' | 'user' // User role from Firestore
    error?: 'RefreshAccessTokenError'
  }
}
