/**
 * API route for video chapters operations.
 *
 * PUT: Update the video chapters (edited by user or generated by AI)
 *
 * Chapters are stored as Array<{ timestamp: string, title: string }>.
 *
 * @see processamento_video.md - Fase 4 - Capitulos
 */

import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

import { auth } from '@/lib/auth'
import { getVideoAdmin, updateVideoAdmin } from '@/lib/firebase/videos-admin'
import { PODCAST_ID } from '@/lib/firebase/config'
import { log } from '@/lib/logger'
import { ChapterSchema } from '@/lib/schemas'
import {
  authExpiredResponse,
  notFoundResponse,
  handleVideoFieldError,
} from '@/lib/api/video-field-handler'

/**
 * Schema for validating chapters update request body.
 */
const ChaptersUpdateSchema = z.object({
  chapters: z
    .array(ChapterSchema)
    .min(1, 'Pelo menos 1 capitulo é necessario')
    .max(20, 'Maximo de 20 capitulos'),
})

export const runtime = 'nodejs' // REQUIRED for firebase-admin

interface RouteContext {
  params: Promise<{ videoId: string }>
}

/**
 * PUT /api/videos/[videoId]/chapters
 *
 * Updates the chapters for a video.
 * Used when user edits chapter titles in Phase 4.
 */
export async function PUT(
  request: NextRequest,
  context: RouteContext
): Promise<NextResponse> {
  const session = await auth()
  if (!session) {
    return authExpiredResponse()
  }

  const { videoId } = await context.params

  try {
    const body = await request.json()

    // Validate chapters with Zod BEFORE persisting
    const { chapters } = ChaptersUpdateSchema.parse(body)

    // Check video exists
    const video = await getVideoAdmin(PODCAST_ID, videoId)
    if (!video) {
      return notFoundResponse('Video')
    }

    // Update video with new chapters
    await updateVideoAdmin(PODCAST_ID, videoId, { chapters })

    log('INFO', 'Video chapters updated', {
      videoId,
      chapterCount: chapters.length,
    })

    return NextResponse.json({
      data: {
        videoId,
        chapterCount: chapters.length,
      },
    })
  } catch (error) {
    return handleVideoFieldError(error, 'chapters', videoId)
  }
}
