/**
 * Social Admin — Global catalog and per-video social post operations.
 *
 * - `getSocialNetworks()`: Reads from global `socialNetworks` collection (no podcastId).
 * - `getSocialPosts()`, `upsertSocialPost()`: Reads/writes subcollection
 *   `podcasts/{podcastId}/videos/{videoId}/socialPosts/{networkId}`.
 *
 * @see SocialNetworkSchema, SocialPostSchema for validation rules
 */
import { FieldValue } from 'firebase-admin/firestore'

import { log } from '@/lib/logger'
import { SocialNetworkSchema, SocialPostSchema, SocialPostUpdateSchema } from '@/lib/schemas'
import type { SocialNetwork, SocialPost, SocialPostUpdate } from '@/types/social'

import { getAdminDb } from './admin'
import { PODCAST_ID } from './config'

/**
 * Helper to get the socialPosts subcollection reference for a video.
 *
 * Path: `podcasts/{podcastId}/videos/{videoId}/socialPosts`
 */
function getSocialPostsCollection(videoId: string) {
  const db = getAdminDb()
  return db
    .collection('podcasts').doc(PODCAST_ID)
    .collection('videos').doc(videoId)
    .collection('socialPosts')
}

/**
 * Gets all available social networks from the global catalog.
 *
 * Reads from the global `socialNetworks` collection (not per-podcast).
 * Invalid documents are logged as warnings and skipped.
 *
 * @returns Array of validated SocialNetwork, ordered by name ascending
 */
export async function getSocialNetworks(): Promise<SocialNetwork[]> {
  const db = getAdminDb()
  const snapshot = await db.collection('socialNetworks').orderBy('name').get()

  if (snapshot.empty) {
    log('INFO', 'No social networks found in global catalog')
    return []
  }

  const networks: SocialNetwork[] = []
  for (const doc of snapshot.docs) {
    const parsed = SocialNetworkSchema.safeParse({ ...doc.data(), id: doc.id })
    if (parsed.success) {
      networks.push(parsed.data)
    } else {
      log('WARN', 'Invalid social network document skipped', {
        networkId: doc.id,
        issues: parsed.error.issues,
      })
    }
  }

  log('INFO', 'Social networks fetched', { count: networks.length })
  return networks
}

/**
 * Gets all social posts for a video from the socialPosts subcollection.
 *
 * Path: `podcasts/{podcastId}/videos/{videoId}/socialPosts`
 * Invalid documents are logged as warnings and skipped (safeParse pattern).
 *
 * @param videoId - The video document ID
 * @returns Array of validated SocialPost (may be empty)
 */
export async function getSocialPosts(videoId: string): Promise<SocialPost[]> {
  const snapshot = await getSocialPostsCollection(videoId).get()

  if (snapshot.empty) {
    log('INFO', 'No social posts found', { videoId })
    return []
  }

  const posts: SocialPost[] = []
  for (const doc of snapshot.docs) {
    const parsed = SocialPostSchema.safeParse({ ...doc.data(), networkId: doc.id })
    if (parsed.success) {
      posts.push(parsed.data)
    } else {
      log('WARN', 'Invalid social post document skipped', {
        videoId,
        networkId: doc.id,
        issues: parsed.error.issues,
      })
    }
  }

  log('INFO', 'Social posts fetched', { videoId, count: posts.length })
  return posts
}

/**
 * Creates or updates a social post for a video and network.
 *
 * Path: `podcasts/{podcastId}/videos/{videoId}/socialPosts/{networkId}`
 * Uses set with merge to support both create and update scenarios.
 * Sets `processedBy: 'manual'` and `updatedAt` via server timestamp.
 *
 * @param videoId - The video document ID
 * @param networkId - The social network ID (e.g., 'instagram')
 * @param data - The social post update data (cta, body, hashtags)
 */
export async function upsertSocialPost(
  videoId: string,
  networkId: string,
  data: SocialPostUpdate
): Promise<void> {
  const validated = SocialPostUpdateSchema.parse(data)

  const docRef = getSocialPostsCollection(videoId).doc(networkId)

  await docRef.set(
    {
      ...validated,
      networkId,
      processedBy: 'manual',
      updatedAt: FieldValue.serverTimestamp(),
    },
    { merge: true }
  )

  log('INFO', 'Social post upserted', { videoId, networkId, processedBy: 'manual' })
}

/**
 * Saves a social post generated by LLM.
 *
 * Separate from `upsertSocialPost` which hardcodes `processedBy: 'manual'`.
 * Sets `processedBy: 'llm'`, `generatedAt`, and `updatedAt` via server timestamp.
 *
 * @param videoId - The video document ID
 * @param networkId - The social network ID (e.g., 'instagram')
 * @param data - The LLM-generated post data (cta, body, hashtags)
 * @param additionalContext - Optional user instruction used during generation
 */
export async function saveSocialPostFromLLM(
  videoId: string,
  networkId: string,
  data: { cta: string; body: string; hashtags: string[] },
  additionalContext?: string
): Promise<void> {
  const validated = SocialPostUpdateSchema.parse(data)
  const docRef = getSocialPostsCollection(videoId).doc(networkId)

  const docData: Record<string, unknown> = {
    ...validated,
    networkId,
    processedBy: 'llm',
    generatedAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
  }

  if (additionalContext !== undefined) {
    docData.additionalContext = additionalContext
  }

  await docRef.set(docData, { merge: true })

  log('INFO', 'Social post saved from LLM', { videoId, networkId, processedBy: 'llm' })
}
