/**
 * API route for video description operations.
 *
 * PUT: Update the video description (edited by user or generated by AI)
 *
 * Description is stored flat on the video document at root level.
 *
 * @see processamento_video.md - Fase 6 - Descricao
 */

import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

import { auth } from '@/lib/auth'
import { getVideoAdmin, updateVideoAdmin } from '@/lib/firebase/videos-admin'
import { PODCAST_ID } from '@/lib/firebase/config'
import { log } from '@/lib/logger'
import {
  authExpiredResponse,
  notFoundResponse,
  handleVideoFieldError,
} from '@/lib/api/video-field-handler'

/**
 * Schema for validating description update request body.
 */
const DescriptionUpdateSchema = z.object({
  description: z
    .string()
    .min(1, 'Descricao obrigatoria')
    .max(5000, 'Descricao muito longa'),
})

export const runtime = 'nodejs' // REQUIRED for firebase-admin

interface RouteContext {
  params: Promise<{ videoId: string }>
}

/**
 * PUT /api/videos/[videoId]/description
 *
 * Updates the description for a video.
 * Used when user edits the AI-generated description in Phase 6.
 */
export async function PUT(
  request: NextRequest,
  context: RouteContext
): Promise<NextResponse> {
  const session = await auth()
  if (!session) {
    return authExpiredResponse()
  }

  const { videoId } = await context.params

  try {
    const body = await request.json()

    // Validate description with Zod BEFORE persisting
    const { description } = DescriptionUpdateSchema.parse(body)

    // Check video exists
    const video = await getVideoAdmin(PODCAST_ID, videoId)
    if (!video) {
      return notFoundResponse('Video')
    }

    // Update video with new description
    await updateVideoAdmin(PODCAST_ID, videoId, { description })

    log('INFO', 'Video description updated', {
      videoId,
      descriptionLength: description.length,
    })

    return NextResponse.json({
      data: {
        videoId,
        descriptionLength: description.length,
      },
    })
  } catch (error) {
    return handleVideoFieldError(error, 'descricao', videoId)
  }
}
