'use client'

import { useCallback, useEffect, useState } from 'react'
import { AlertTriangleIcon, ImageIcon, ImageOff, Loader2 } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import {
  GeneratedVersionsGallery,
  type GeneratedThumbnailVersion,
} from '@/components/wizard/thumbnail/generated-versions-gallery'
import { GuestPhotoUploader } from '@/components/wizard/thumbnail/guest-photo-uploader'
import { ManualUploadDropzone } from '@/components/wizard/thumbnail/manual-upload-dropzone'
import { ThumbnailLightbox } from '@/components/wizard/thumbnail/thumbnail-lightbox'
import {
  GenerateImageCard,
  __setImagePollIntervalForTesting,
} from '@/components/wizard/images/generate-image-card'
import { log } from '@/lib/logger'
import { getNextPhaseNameForType } from '@/lib/wizard'
import type { VideoTypeForWizard } from '@/lib/wizard/types'

/**
 * @internal — usado apenas em testes. Re-exportado do card de geração, que
 * passou a ser o dono do polling na Story 28.3; o nome antigo continua válido
 * para não tocar na suíte do Epic 22.
 */
export const __setThumbnailPollIntervalForTesting = __setImagePollIntervalForTesting
import type { ThumbnailPromptField } from '@/types/podcast'
import type { Video } from '@/types/video'

interface PhaseThumbnailProps {
  video: Video
  /**
   * Podcast features — used to compute the next-phase label on the advance
   * button (episode: Thumbnail → Links; cut: Thumbnail → Publicar). Epic 26.
   */
  features?: { thumbnailGeneration?: boolean; extraImagesGeneration?: boolean }
  /**
   * Disparado após persistir com sucesso a thumbnail selecionada em
   * `video.storageThumbnailUrl`. Recebe o novo URL final pra que o
   * orquestrador atualize o estado local antes de avançar pra Phase 8.
   *
   * Story 22.3g introduziu o payload — antes era `() => void`. O pai
   * é responsável por avançar a fase via `completePhaseAndAdvance`.
   */
  onAdvance?: (payload: { newStorageUrl: string }) => void
  /**
   * URL of the currently selected thumbnail (either generated by the LLM or uploaded
   * manually by the producer). When provided, takes precedence over any thumbnail
   * the producer generates locally in this session (used to hydrate the phase when
   * the producer revisits a video that already has a saved thumbnail).
   *
   * Story 22.3a/b delivered the layout. 22.3c activates Caminho 1 (Gerar) via a
   * stub endpoint; 22.3d..g cover history, upload and persistence.
   */
  selectedThumbnailUrl?: string
  className?: string
}

/**
 * Phase Thumbnail — Epic 22 / Story 22.3 (split into sub-stories 22.3a..22.3g).
 *
 * 22.3a delivered the skeleton + wizard integration. 22.3b added the dual layout:
 * Base/Referência previews + duas seções (Gerar/Upload) + Thumbnail selecionada.
 * 22.3c activates Caminho 1 (Gerar) via stub endpoint com feedback temporal.
 *
 * 22.3d (this revision) adds the generated-versions gallery: cada chamada a
 * Gerar adiciona uma entrada ao histórico (não substitui a anterior). Click
 * numa miniatura troca a versão selecionada sem perder as outras. A versão
 * recém-gerada é auto-selecionada. O upload manual chega na 22.3e.
 *
 * Gated by `podcast.features.thumbnailGeneration` e renderizada apenas para
 * `episode` e `cut` (ver `getPhasesForVideoTypeWithFeatures`).
 */
export function PhaseThumbnail({ video, features, onAdvance, selectedThumbnailUrl, className }: PhaseThumbnailProps) {
  const [config, setConfig] = useState<ThumbnailPromptField | null>(null)
  const [configLoaded, setConfigLoaded] = useState(false)
  const [versions, setVersions] = useState<GeneratedThumbnailVersion[]>([])
  const [selectedVersionUrl, setSelectedVersionUrl] = useState<string | null>(null)
  const [lightboxUrl, setLightboxUrl] = useState<string | null>(null)
  const [guestPhotoUrl, setGuestPhotoUrl] = useState<string | null>(null)
  const [isSelecting, setIsSelecting] = useState(false)
  const [selectError, setSelectError] = useState<string | null>(null)
  // Local generation/selection always wins over the hydrated `selectedThumbnailUrl`
  // prop. Sem isso, um vídeo com `storageThumbnailUrl` pré-existente (ex.: base64
  // legado da YouTube — TD-5) mascararia a thumbnail recém-gerada e o produtor não
  // veria mudança ao clicar Gerar.
  const effectiveSelectedUrl = selectedVersionUrl ?? selectedThumbnailUrl ?? undefined
  const canAdvance = Boolean(effectiveSelectedUrl)
  const videoType = video.videoType
  const standalone = video.standalone === true

  useEffect(() => {
    if (videoType !== 'episode' && videoType !== 'cut') {
      setConfigLoaded(true)
      return
    }
    let cancelled = false
    fetch('/api/podcast')
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        if (cancelled) return
        const prompts = d?.data?.prompts
        // Avulso (Epic 25) usa o bucket `standalone` quando completo, com fallback
        // pro bucket do videoType — espelha getThumbnailConfig na geração, pra a
        // UI refletir exatamente a config que será usada.
        const standaloneThumb = standalone
          ? (prompts?.standalone?.thumbnail as ThumbnailPromptField | undefined)
          : undefined
        const thumb =
          standaloneThumb?.description && standaloneThumb?.expectedOutput
            ? standaloneThumb
            : (prompts?.[videoType]?.thumbnail as ThumbnailPromptField | undefined)
        setConfig(thumb ?? null)
        setConfigLoaded(true)
      })
      .catch((err) => {
        if (cancelled) return
        log('WARN', 'Failed to load thumbnail config', {
          videoType,
          error: err instanceof Error ? err.message : String(err),
        })
        setConfigLoaded(true)
      })
    return () => {
      cancelled = true
    }
  }, [videoType, standalone])

  const handleGenerated = useCallback((payload: { url: string; observation: string | undefined }) => {
    const version: GeneratedThumbnailVersion = {
      id: `gen-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      url: payload.url,
      observation: payload.observation,
      timestamp: new Date(),
      source: 'generated',
    }
    setVersions((prev) => [...prev, version])
    setSelectedVersionUrl(version.url)
  }, [])

  const handleUploaded = useCallback((payload: { url: string }) => {
    const version: GeneratedThumbnailVersion = {
      id: `up-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      url: payload.url,
      observation: undefined,
      timestamp: new Date(),
      source: 'upload',
    }
    setVersions((prev) => [...prev, version])
    setSelectedVersionUrl(version.url)
  }, [])

  const handleSelectVersion = useCallback((url: string) => {
    setSelectedVersionUrl(url)
  }, [])

  const handleOpenLightbox = useCallback((url: string) => {
    setLightboxUrl(url)
  }, [])

  const handleCloseLightbox = useCallback(() => {
    setLightboxUrl(null)
  }, [])

  /**
   * Persiste a thumbnail selecionada e avança pra Phase 8.
   *
   * Chama `POST /api/wizard/thumbnail/select` que copia o arquivo de staging
   * pro path final e atualiza `video.storageThumbnailUrl` no Firestore. Em
   * sucesso, repassa o novo URL final pro pai via `onAdvance({ newStorageUrl })`
   * pra que o orchestrator atualize o `videoData` antes de navegar. Em erro,
   * mostra mensagem inline e mantém o produtor na fase.
   */
  const handleContinuar = useCallback(async () => {
    if (!effectiveSelectedUrl || isSelecting) return
    setSelectError(null)
    setIsSelecting(true)
    try {
      const response = await fetch('/api/wizard/thumbnail/select', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ videoId: video.id, selectedThumbnailUrl: effectiveSelectedUrl }),
      })
      if (!response.ok) {
        let message = 'Falha ao salvar a thumbnail selecionada. Tente novamente.'
        try {
          const payload = await response.json()
          if (payload?.error?.message) message = payload.error.message
        } catch {
          // ignore parse error
        }
        setSelectError(message)
        log('WARN', 'Thumbnail select failed', { videoId: video.id, status: response.status })
        return
      }
      const data = (await response.json()) as { thumbnailUrl?: string }
      if (!data?.thumbnailUrl) {
        setSelectError('Resposta inválida do servidor. Tente novamente.')
        return
      }
      onAdvance?.({ newStorageUrl: data.thumbnailUrl })
      log('INFO', 'Thumbnail selected and persisted', { videoId: video.id })
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Erro inesperado.'
      setSelectError(`Erro inesperado: ${message}`)
      log('WARN', 'Thumbnail select threw', {
        videoId: video.id,
        error: err instanceof Error ? err.message : String(err),
      })
    } finally {
      setIsSelecting(false)
    }
  }, [effectiveSelectedUrl, isSelecting, onAdvance, video.id])

  return (
    <div className={className} data-testid="phase-thumbnail" data-video-id={video.id}>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon className="h-5 w-5" />
            Thumbnail
          </CardTitle>
          <CardDescription>
            Gere o thumbnail do vídeo via IAra ou faça upload de uma imagem própria. A
            thumbnail selecionada é enviada ao YouTube na próxima fase.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <ReferencesPanel config={config} configLoaded={configLoaded} />

          <div className="flex flex-col gap-4">
            <GeneratePathCard
              videoId={video.id}
              videoType={videoType}
              guestPhotoUrl={guestPhotoUrl}
              onGuestPhotoChange={setGuestPhotoUrl}
              onGenerated={handleGenerated}
            />

            <GeneratedVersionsGallery
              versions={versions}
              selectedUrl={effectiveSelectedUrl}
              onSelect={handleSelectVersion}
              onPreview={handleOpenLightbox}
            />

            <ManualUploadDropzone videoId={video.id} onUploaded={handleUploaded} />
          </div>

          <SelectedThumbnailSummary
            selectedThumbnailUrl={effectiveSelectedUrl}
            onPreview={handleOpenLightbox}
          />

          {selectError && (
            <div
              className="flex items-start gap-2 rounded-md border border-destructive/50 bg-destructive/10 p-2 text-xs text-destructive"
              data-testid="select-error"
            >
              <AlertTriangleIcon className="h-4 w-4 mt-0.5 shrink-0" />
              <span>{selectError}</span>
            </div>
          )}

          <div className="flex justify-end">
            <Button
              onClick={handleContinuar}
              disabled={!canAdvance || isSelecting}
              data-testid="continuar-publicar"
            >
              {isSelecting ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Salvando seleção...
                </>
              ) : (
                `Continuar para ${getNextPhaseNameForType('thumbnail', video.videoType, features) ?? 'Publicar'}`
              )}
            </Button>
          </div>
        </CardContent>
      </Card>

      <ThumbnailLightbox url={lightboxUrl} onClose={handleCloseLightbox} />
    </div>
  )
}

interface ReferencesPanelProps {
  config: ThumbnailPromptField | null
  configLoaded: boolean
}

function ReferencesPanel({ config, configLoaded }: ReferencesPanelProps) {
  if (!configLoaded) {
    return (
      <div className="rounded-md border bg-muted/30 p-4 text-sm text-muted-foreground" data-testid="references-loading">
        Carregando referências configuradas...
      </div>
    )
  }
  const hasBase = Boolean(config?.baseImageUrl)
  const hasReference = Boolean(config?.referenceImageUrl)
  if (!hasBase && !hasReference) {
    return (
      <div className="rounded-md border bg-muted/30 p-4 text-sm" data-testid="references-empty">
        <p className="font-medium">Nenhuma imagem de referência configurada (opcional).</p>
        <p className="mt-1 text-muted-foreground">
          A geração via IAra funciona mesmo assim — só não terá contexto visual do branding.
          Para guiar o visual, configure <strong>Thumbnail Base</strong> e/ou <strong>Thumbnail
          Referência</strong> em Settings → Prompts por Tipo de Vídeo → este tipo de vídeo →
          Geração de Thumbnail (imagem).
        </p>
      </div>
    )
  }
  return (
    <div className="rounded-md border bg-muted/30 p-4" data-testid="references-panel">
      <p className="text-sm font-medium mb-3">Imagens de referência configuradas</p>
      <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
        <ReferenceSlot label="Base" url={config?.baseImageUrl} testid="reference-base" />
        <ReferenceSlot label="Referência" url={config?.referenceImageUrl} testid="reference-reference" />
      </div>
    </div>
  )
}

interface ReferenceSlotProps {
  label: string
  url: string | undefined
  testid: string
}

function ReferenceSlot({ label, url, testid }: ReferenceSlotProps) {
  return (
    <div className="flex items-start gap-3" data-testid={testid}>
      {url ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={url}
          alt={`Preview ${label}`}
          className="h-20 w-auto rounded border bg-muted object-cover"
        />
      ) : (
        <div className="h-20 w-20 rounded border bg-muted flex items-center justify-center text-xs text-muted-foreground">
          <ImageOff className="h-4 w-4" />
        </div>
      )}
      <div className="text-xs">
        <p className="font-medium">{label}</p>
        <p className="text-muted-foreground">{url ? 'Configurada' : 'Não configurada'}</p>
      </div>
    </div>
  )
}

interface GeneratePathCardProps {
  videoId: string
  /**
   * Tipo do vídeo — usado pra gatear o uploader da foto do convidado, que só
   * faz sentido em cortes (cuts).
   */
  videoType: VideoTypeForWizard | undefined
  /**
   * URL atual da foto do convidado (apenas cortes). Quando definida, é
   * incluída como reference extra no body do POST /generate.
   */
  guestPhotoUrl: string | null
  onGuestPhotoChange: (url: string | null) => void
  /**
   * Disparado a cada sucesso de geração. Repassa também a observação usada
   * (trimada — undefined se vazia) pra que a galeria de versões mostre ao
   * lado da miniatura. Story 22.3d depende dessa informação.
   */
  onGenerated: (payload: { url: string; observation: string | undefined }) => void
}

/**
 * Gerar com IAra (Story 22.3c + 22.3d; extraído na Story 28.3).
 *
 * Wrapper fino sobre `GenerateImageCard`, que passou a ser o dono do fluxo
 * POST → job → polling. Aqui sobra só o que é específico do thumbnail: o
 * uploader da foto do convidado (cortes) e o `guestPhotoUrl` no body.
 */
function GeneratePathCard({ videoId, videoType, guestPhotoUrl, onGuestPhotoChange, onGenerated }: GeneratePathCardProps) {
  return (
    <GenerateImageCard
      videoId={videoId}
      endpoint="/api/wizard/thumbnail/generate"
      extraBody={{ guestPhotoUrl: guestPhotoUrl ?? undefined }}
      onGenerated={onGenerated}
    >
      {videoType === 'cut' && (
        <GuestPhotoUploader
          videoId={videoId}
          currentUrl={guestPhotoUrl ?? undefined}
          onChange={onGuestPhotoChange}
        />
      )}
    </GenerateImageCard>
  )
}


interface SelectedThumbnailSummaryProps {
  selectedThumbnailUrl?: string
  /** Click na imagem abre o lightbox em tamanho real para avaliação. */
  onPreview?: (url: string) => void
}

function SelectedThumbnailSummary({ selectedThumbnailUrl, onPreview }: SelectedThumbnailSummaryProps) {
  return (
    <div className="rounded-md border bg-card p-4" data-testid="selected-summary">
      <p className="text-sm font-medium mb-2">Thumbnail selecionada</p>
      {selectedThumbnailUrl ? (
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={() => onPreview?.(selectedThumbnailUrl)}
            data-testid="selected-preview-button"
            className="cursor-zoom-in rounded focus:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            aria-label="Ver thumbnail selecionada em tamanho real"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={selectedThumbnailUrl}
              alt="Thumbnail selecionada"
              className="h-24 w-auto rounded border bg-muted object-cover"
            />
          </button>
          <p className="text-xs text-muted-foreground">
            Pronta para publicar. Clique na imagem para ver em tamanho real.
          </p>
        </div>
      ) : (
        <p className="text-xs text-muted-foreground">
          Nenhuma thumbnail selecionada ainda. Use um dos dois caminhos acima.
        </p>
      )}
    </div>
  )
}
