'use client'

import { useState, useEffect, useCallback } from 'react'
import {
  ArrowRightIcon,
  RefreshCwIcon,
  AlertTriangleIcon,
  TagIcon,
  XIcon,
  PlusIcon,
  Loader2Icon,
} from 'lucide-react'

import { log } from '@/lib/logger'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import type { UseWizardReturn } from '@/hooks/use-wizard'
import type { Video } from '@/types/video'
import type { Phase7Response } from '@/lib/llm/types'

import { getNextPhaseName } from '@/lib/wizard'

import { ProcessingSpinner } from '../processing-spinner'

interface Phase7TagsProps {
  wizard: UseWizardReturn
  video: Video
  /** Result from LLM processing (null while processing or if error) */
  tagsResult: Phase7Response | null
  /** Error message if processing failed */
  error?: string | null
  /** Callback to retry processing after error */
  onRetry?: () => void
  /** Callback when revalidation is requested with additional context */
  onRevalidate?: (additionalContext: string) => void
  /** Callback when tags are changed. Returns promise for advance sync. */
  onTagsChange?: (tags: string[]) => Promise<void>
  className?: string
}

const MAX_TOTAL_CHARS = 500
const MAX_ADDITIONAL_CONTEXT_CHARS = 200

/**
 * Phase 7: Tags - Reprocessable (Type 1)
 *
 * Displays SEO-optimized tags generated by LLM for user editing.
 *
 * Key features:
 * - Auto-processes on phase entry
 * - Tags displayed as removable chips/badges
 * - Can add new tags manually
 * - 500 character limit (YouTube requirement)
 * - Additional context input for revalidation
 * - Revalidar button (no confirmation needed - last LLM phase)
 * - Type 1: Can be reprocessed multiple times
 *
 * @see processamento_video.md - Fase 7 - Tags
 */
export function Phase7Tags({
  wizard,
  video,
  tagsResult,
  error,
  onRetry,
  onRevalidate,
  onTagsChange,
  className,
}: Phase7TagsProps) {
  const hasResult = tagsResult !== null
  const hasError = !!error

  // Tags state - initialize from result or video.tags
  const [tags, setTags] = useState<string[]>(tagsResult?.tags ?? video.tags ?? [])

  // New tag input state
  const [newTag, setNewTag] = useState('')

  // Update tags when result changes or when video.tags changes externally
  useEffect(() => {
    if (tagsResult?.tags) {
      setTags(tagsResult.tags)
    } else if (video.tags && video.tags.length > 0) {
      // Sync from video.tags if no tagsResult yet (e.g., returning to phase)
      setTags(video.tags)
    }
  }, [tagsResult?.tags, video.tags])

  // Additional context for revalidation
  const [additionalContext, setAdditionalContext] = useState('')

  // State for advancing to next phase (prevents double clicks)
  const [isAdvancing, setIsAdvancing] = useState(false)

  // Calculate total characters used
  const totalChars = tags.join(',').length
  const remainingChars = MAX_TOTAL_CHARS - totalChars
  const remainingContextChars = MAX_ADDITIONAL_CONTEXT_CHARS - additionalContext.length

  // Check if can advance: result must exist and at least 1 tag
  const canAdvance = hasResult && tags.length > 0 && !hasError && !isAdvancing

  // Handle adding a new tag
  const handleAddTag = useCallback(() => {
    const trimmedTag = newTag.trim()
    if (!trimmedTag) return

    // Check if tag already exists
    if (tags.includes(trimmedTag)) {
      setNewTag('')
      return
    }

    // Check if adding would exceed limit
    const newTotalChars = totalChars + (totalChars > 0 ? 1 : 0) + trimmedTag.length
    if (newTotalChars > MAX_TOTAL_CHARS) {
      return
    }

    const newTags = [...tags, trimmedTag]
    setTags(newTags)
    setNewTag('')
    onTagsChange?.(newTags)
  }, [newTag, tags, totalChars, onTagsChange])

  // Handle removing a tag
  const handleRemoveTag = useCallback(
    (tagToRemove: string) => {
      const newTags = tags.filter((tag) => tag !== tagToRemove)
      setTags(newTags)
      onTagsChange?.(newTags)
    },
    [tags, onTagsChange]
  )

  // Handle Enter key in new tag input
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter') {
        e.preventDefault()
        handleAddTag()
      }
    },
    [handleAddTag]
  )

  const handleAdvanceClick = async () => {
    if (!canAdvance) return
    setIsAdvancing(true)
    // Always save tags before advancing (even if user didn't edit)
    try {
      await onTagsChange?.(tags)
    } catch (error) {
      // Log error but don't block advance - user can still proceed
      log('WARN', 'Failed to save tags on advance, continuing anyway', {
        error: error instanceof Error ? error.message : 'Unknown error',
      })
    }
    wizard.completePhaseAndAdvance(7, { tags })
  }

  const handleRevalidateClick = () => {
    // No confirmation needed for Phase 7 (last LLM phase, no subsequent phases to mark)
    onRevalidate?.(additionalContext)
  }

  return (
    <div className={className}>
      <div className="space-y-4">
        {/* Error state with retry button */}
        {hasError && (
          <Card className="border-destructive">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-destructive">
                Erro na Geracao de Tags
              </CardTitle>
              <CardDescription>
                Nao foi possivel gerar as tags automaticamente.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6">
                <AlertTriangleIcon className="size-12 text-destructive" />
                <p className="text-sm text-muted-foreground text-center">{error}</p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Loading state when no result yet */}
        {!tagsResult && !hasError && (
          <ProcessingSpinner text="Gerando tags otimizadas para SEO..." />
        )}

        {/* Tags list */}
        {tagsResult && !hasError && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <TagIcon className="size-4" />
                Tags Geradas
              </CardTitle>
              <CardDescription>
                Adicione ou remova tags conforme necessario.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Tags as chips */}
              <div className="flex flex-wrap gap-2">
                {tags.map((tag) => (
                  <Badge
                    key={tag}
                    variant="secondary"
                    className="flex items-center gap-1 px-3 py-1"
                  >
                    {tag}
                    <button
                      type="button"
                      onClick={() => handleRemoveTag(tag)}
                      className="ml-1 hover:text-destructive transition-colors"
                      aria-label={`Remover tag ${tag}`}
                    >
                      <XIcon className="size-3" />
                    </button>
                  </Badge>
                ))}
                {tags.length === 0 && (
                  <p className="text-sm text-muted-foreground">
                    Nenhuma tag adicionada ainda.
                  </p>
                )}
              </div>

              {/* Add new tag input */}
              <div className="flex gap-2">
                <Input
                  placeholder="Adicionar nova tag..."
                  value={newTag}
                  onChange={(e) => setNewTag(e.target.value)}
                  onKeyDown={handleKeyDown}
                  className="flex-1"
                />
                <Button
                  variant="outline"
                  onClick={handleAddTag}
                  disabled={!newTag.trim() || remainingChars < newTag.trim().length + 1}
                >
                  <PlusIcon className="size-4 mr-1" />
                  Adicionar
                </Button>
              </div>

              {/* Character count */}
              <div className="flex justify-end text-xs text-muted-foreground">
                <span className={remainingChars < 50 ? 'text-amber-500' : ''}>
                  {totalChars}/{MAX_TOTAL_CHARS} caracteres usados
                </span>
              </div>

              {/* Additional context input for revalidation */}
              <div className="pt-4 border-t">
                <div className="space-y-2">
                  <Label htmlFor="additional-context" className="text-sm font-medium">
                    Dica para novas tags (opcional)
                  </Label>
                  <Textarea
                    id="additional-context"
                    placeholder="Ex: Foque mais em termos tecnicos, adicione tags em ingles..."
                    value={additionalContext}
                    onChange={(e) => setAdditionalContext(e.target.value)}
                    maxLength={MAX_ADDITIONAL_CONTEXT_CHARS}
                    className="min-h-[80px] resize-none"
                  />
                  <div className="flex justify-between items-center text-xs text-muted-foreground">
                    <span>Use para gerar novas tags com contexto adicional</span>
                    <span className={remainingContextChars < 20 ? 'text-amber-500' : ''}>
                      {remainingContextChars} caracteres restantes
                    </span>
                  </div>
                </div>

                {/* Revalidar button */}
                <div className="mt-3">
                  <Button
                    variant="outline"
                    onClick={handleRevalidateClick}
                    disabled={!onRevalidate}
                  >
                    <RefreshCwIcon className="size-4 mr-2" />
                    Gerar novas tags
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Advance button */}
        <div className="flex justify-end pt-4">
          <Button onClick={handleAdvanceClick} disabled={!canAdvance}>
            {isAdvancing ? (
              <>
                Avançando...
                <Loader2Icon className="size-4 ml-2 animate-spin" />
              </>
            ) : (
              <>
                Avançar para {getNextPhaseName(7)}
                <ArrowRightIcon className="size-4 ml-2" />
              </>
            )}
          </Button>
        </div>
      </div>
    </div>
  )
}
