'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { AlertTriangleIcon, ImageIcon, ImageOff, Loader2, Sparkles } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  GeneratedVersionsGallery,
  type GeneratedThumbnailVersion,
} from '@/components/wizard/thumbnail/generated-versions-gallery'
import { GuestPhotoUploader } from '@/components/wizard/thumbnail/guest-photo-uploader'
import { ManualUploadDropzone } from '@/components/wizard/thumbnail/manual-upload-dropzone'
import { ThumbnailLightbox } from '@/components/wizard/thumbnail/thumbnail-lightbox'
import { log } from '@/lib/logger'
import type { VideoTypeForWizard } from '@/lib/wizard/types'
import type { ThumbnailPromptField } from '@/types/podcast'
import type { Video } from '@/types/video'

interface PhaseThumbnailProps {
  video: Video
  /** Callback when "Continuar para Publicar" is clicked. Disabled until a thumbnail is selected. */
  onAdvance?: () => void
  /**
   * URL of the currently selected thumbnail (either generated by the LLM or uploaded
   * manually by the producer). When provided, takes precedence over any thumbnail
   * the producer generates locally in this session (used to hydrate the phase when
   * the producer revisits a video that already has a saved thumbnail).
   *
   * Story 22.3a/b delivered the layout. 22.3c activates Caminho 1 (Gerar) via a
   * stub endpoint; 22.3d..g cover history, upload and persistence.
   */
  selectedThumbnailUrl?: string
  className?: string
}

/**
 * Phase Thumbnail — Epic 22 / Story 22.3 (split into sub-stories 22.3a..22.3g).
 *
 * 22.3a delivered the skeleton + wizard integration. 22.3b added the dual layout:
 * Base/Referência previews + duas seções (Gerar/Upload) + Thumbnail selecionada.
 * 22.3c activates Caminho 1 (Gerar) via stub endpoint com feedback temporal.
 *
 * 22.3d (this revision) adds the generated-versions gallery: cada chamada a
 * Gerar adiciona uma entrada ao histórico (não substitui a anterior). Click
 * numa miniatura troca a versão selecionada sem perder as outras. A versão
 * recém-gerada é auto-selecionada. O upload manual chega na 22.3e.
 *
 * Gated by `podcast.features.thumbnailGeneration` e renderizada apenas para
 * `episode` e `cut` (ver `getPhasesForVideoTypeWithFeatures`).
 */
export function PhaseThumbnail({ video, onAdvance, selectedThumbnailUrl, className }: PhaseThumbnailProps) {
  const [config, setConfig] = useState<ThumbnailPromptField | null>(null)
  const [configLoaded, setConfigLoaded] = useState(false)
  const [versions, setVersions] = useState<GeneratedThumbnailVersion[]>([])
  const [selectedVersionUrl, setSelectedVersionUrl] = useState<string | null>(null)
  const [lightboxUrl, setLightboxUrl] = useState<string | null>(null)
  const [guestPhotoUrl, setGuestPhotoUrl] = useState<string | null>(null)
  // Local generation/selection always wins over the hydrated `selectedThumbnailUrl`
  // prop. Sem isso, um vídeo com `storageThumbnailUrl` pré-existente (ex.: base64
  // legado da YouTube — TD-5) mascararia a thumbnail recém-gerada e o produtor não
  // veria mudança ao clicar Gerar.
  const effectiveSelectedUrl = selectedVersionUrl ?? selectedThumbnailUrl ?? undefined
  const canAdvance = Boolean(effectiveSelectedUrl)
  const videoType = video.videoType

  useEffect(() => {
    if (videoType !== 'episode' && videoType !== 'cut') {
      setConfigLoaded(true)
      return
    }
    let cancelled = false
    fetch('/api/podcast')
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        if (cancelled) return
        const thumb = d?.data?.prompts?.[videoType]?.thumbnail as ThumbnailPromptField | undefined
        setConfig(thumb ?? null)
        setConfigLoaded(true)
      })
      .catch((err) => {
        if (cancelled) return
        log('WARN', 'Failed to load thumbnail config', {
          videoType,
          error: err instanceof Error ? err.message : String(err),
        })
        setConfigLoaded(true)
      })
    return () => {
      cancelled = true
    }
  }, [videoType])

  const handleGenerated = useCallback((payload: { url: string; observation: string | undefined }) => {
    const version: GeneratedThumbnailVersion = {
      id: `gen-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      url: payload.url,
      observation: payload.observation,
      timestamp: new Date(),
      source: 'generated',
    }
    setVersions((prev) => [...prev, version])
    setSelectedVersionUrl(version.url)
  }, [])

  const handleUploaded = useCallback((payload: { url: string }) => {
    const version: GeneratedThumbnailVersion = {
      id: `up-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      url: payload.url,
      observation: undefined,
      timestamp: new Date(),
      source: 'upload',
    }
    setVersions((prev) => [...prev, version])
    setSelectedVersionUrl(version.url)
  }, [])

  const handleSelectVersion = useCallback((url: string) => {
    setSelectedVersionUrl(url)
  }, [])

  const handleOpenLightbox = useCallback((url: string) => {
    setLightboxUrl(url)
  }, [])

  const handleCloseLightbox = useCallback(() => {
    setLightboxUrl(null)
  }, [])

  return (
    <div className={className} data-testid="phase-thumbnail" data-video-id={video.id}>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon className="h-5 w-5" />
            Thumbnail
          </CardTitle>
          <CardDescription>
            Gere o thumbnail do vídeo via IAra ou faça upload de uma imagem própria. A
            thumbnail selecionada é enviada ao YouTube na próxima fase.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <ReferencesPanel config={config} configLoaded={configLoaded} />

          <div className="flex flex-col gap-4">
            <GeneratePathCard
              videoId={video.id}
              videoType={videoType}
              guestPhotoUrl={guestPhotoUrl}
              onGuestPhotoChange={setGuestPhotoUrl}
              onGenerated={handleGenerated}
            />

            <GeneratedVersionsGallery
              versions={versions}
              selectedUrl={effectiveSelectedUrl}
              onSelect={handleSelectVersion}
              onPreview={handleOpenLightbox}
            />

            <ManualUploadDropzone videoId={video.id} onUploaded={handleUploaded} />
          </div>

          <SelectedThumbnailSummary
            selectedThumbnailUrl={effectiveSelectedUrl}
            onPreview={handleOpenLightbox}
          />

          <div className="flex justify-end">
            <Button onClick={onAdvance} disabled={!canAdvance}>
              Continuar para Publicar
            </Button>
          </div>
        </CardContent>
      </Card>

      <ThumbnailLightbox url={lightboxUrl} onClose={handleCloseLightbox} />
    </div>
  )
}

interface ReferencesPanelProps {
  config: ThumbnailPromptField | null
  configLoaded: boolean
}

function ReferencesPanel({ config, configLoaded }: ReferencesPanelProps) {
  if (!configLoaded) {
    return (
      <div className="rounded-md border bg-muted/30 p-4 text-sm text-muted-foreground" data-testid="references-loading">
        Carregando referências configuradas...
      </div>
    )
  }
  const hasBase = Boolean(config?.baseImageUrl)
  const hasReference = Boolean(config?.referenceImageUrl)
  if (!hasBase && !hasReference) {
    return (
      <div className="rounded-md border bg-muted/30 p-4 text-sm" data-testid="references-empty">
        <p className="font-medium">Nenhuma imagem de referência configurada.</p>
        <p className="mt-1 text-muted-foreground">
          Configure <strong>Thumbnail Base</strong> e <strong>Thumbnail Referência</strong> em Settings →
          Prompts por Tipo de Vídeo → este tipo de vídeo → Geração de Thumbnail (imagem). Sem isso a
          geração via IAra não tem contexto visual do branding.
        </p>
      </div>
    )
  }
  return (
    <div className="rounded-md border bg-muted/30 p-4" data-testid="references-panel">
      <p className="text-sm font-medium mb-3">Imagens de referência configuradas</p>
      <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
        <ReferenceSlot label="Base" url={config?.baseImageUrl} testid="reference-base" />
        <ReferenceSlot label="Referência" url={config?.referenceImageUrl} testid="reference-reference" />
      </div>
    </div>
  )
}

interface ReferenceSlotProps {
  label: string
  url: string | undefined
  testid: string
}

function ReferenceSlot({ label, url, testid }: ReferenceSlotProps) {
  return (
    <div className="flex items-start gap-3" data-testid={testid}>
      {url ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={url}
          alt={`Preview ${label}`}
          className="h-20 w-auto rounded border bg-muted object-cover"
        />
      ) : (
        <div className="h-20 w-20 rounded border bg-muted flex items-center justify-center text-xs text-muted-foreground">
          <ImageOff className="h-4 w-4" />
        </div>
      )}
      <div className="text-xs">
        <p className="font-medium">{label}</p>
        <p className="text-muted-foreground">{url ? 'Configurada' : 'Não configurada'}</p>
      </div>
    </div>
  )
}

interface GeneratePathCardProps {
  videoId: string
  /**
   * Tipo do vídeo — usado pra gatear o uploader da foto do convidado, que só
   * faz sentido em cortes (cuts).
   */
  videoType: VideoTypeForWizard | undefined
  /**
   * URL atual da foto do convidado (apenas cortes). Quando definida, é
   * incluída como reference extra no body do POST /generate.
   */
  guestPhotoUrl: string | null
  onGuestPhotoChange: (url: string | null) => void
  /**
   * Disparado a cada sucesso de geração. Repassa também a observação usada
   * (trimada — undefined se vazia) pra que a galeria de versões mostre ao
   * lado da miniatura. Story 22.3d depende dessa informação.
   */
  onGenerated: (payload: { url: string; observation: string | undefined }) => void
}

/**
 * Gerar com IAra (Story 22.3c + 22.3d).
 *
 * Renderiza textarea de observações e botão Gerar Thumbnail. Durante a chamada
 * ao stub, mantém um timer de tempo decorrido que troca a mensagem do spinner
 * em 30s e 60s (mesmo padrão das fases LLM). Em sucesso, repassa URL + observação
 * via `onGenerated` — o pai adiciona ao histórico de versões. Em erro, mostra a
 * mensagem com botão de tentar novamente; upload manual permanece disponível
 * como alternativa quando 22.3e entrar.
 */
function GeneratePathCard({ videoId, videoType, guestPhotoUrl, onGuestPhotoChange, onGenerated }: GeneratePathCardProps) {
  const [observation, setObservation] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [elapsedSeconds, setElapsedSeconds] = useState(0)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  useEffect(() => {
    if (isGenerating) {
      setElapsedSeconds(0)
      timerRef.current = setInterval(() => {
        setElapsedSeconds((s) => s + 1)
      }, 1000)
    } else if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current)
        timerRef.current = null
      }
    }
  }, [isGenerating])

  const spinnerText =
    elapsedSeconds >= 60
      ? 'Geração em andamento. Aguarde, não feche a página.'
      : elapsedSeconds >= 30
        ? 'Gerando thumbnail — modelos preview podem demorar um pouco mais...'
        : 'Gerando thumbnail com IAra...'

  const handleGenerate = useCallback(async () => {
    setError(null)
    setIsGenerating(true)
    try {
      const trimmed = observation.trim()
      const body: { videoId: string; observation?: string; guestPhotoUrl?: string } = { videoId }
      if (trimmed.length > 0) body.observation = trimmed
      if (guestPhotoUrl) body.guestPhotoUrl = guestPhotoUrl

      const response = await fetch('/api/wizard/thumbnail/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      if (!response.ok) {
        let message = 'Falha ao gerar thumbnail. Tente novamente em alguns instantes.'
        try {
          const payload = await response.json()
          if (payload?.error?.message) message = payload.error.message
        } catch {
          // ignore body parse error, fall back to default message
        }
        setError(message)
        log('WARN', 'Thumbnail generation request failed', { videoId, status: response.status })
        return
      }
      const data = (await response.json()) as { thumbnailUrl?: string }
      if (!data?.thumbnailUrl) {
        setError('Resposta inválida do servidor. Tente novamente.')
        return
      }
      const trimmedForPayload = observation.trim()
      onGenerated({
        url: data.thumbnailUrl,
        observation: trimmedForPayload.length > 0 ? trimmedForPayload : undefined,
      })
      log('INFO', 'Thumbnail generated (stub)', { videoId })
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Erro inesperado.'
      setError(`Erro inesperado ao gerar thumbnail: ${message}`)
      log('WARN', 'Thumbnail generation threw', {
        videoId,
        error: err instanceof Error ? err.message : String(err),
      })
    } finally {
      setIsGenerating(false)
    }
  }, [guestPhotoUrl, observation, onGenerated, videoId])

  return (
    <div className="rounded-md border p-4 flex flex-col gap-3" data-testid="path-generate">
      <div className="flex items-center gap-2 font-medium">
        <Sparkles className="h-4 w-4" />
        Gerar com IAra
      </div>
      <p className="text-sm text-muted-foreground">
        Use Base + Referência configuradas + observações suas para o modelo gerar a thumbnail.
      </p>

      <div className="flex flex-col gap-1">
        <Label htmlFor={`thumbnail-observation-${videoId}`} className="text-xs">
          Observações para a IAra (opcional)
        </Label>
        <Textarea
          id={`thumbnail-observation-${videoId}`}
          data-testid="thumbnail-observation"
          value={observation}
          onChange={(e) => setObservation(e.target.value)}
          placeholder="Ex.: destaque o convidado, fundo escuro, sem texto..."
          rows={3}
          maxLength={2000}
          disabled={isGenerating}
        />
        <p className="text-[11px] text-muted-foreground">
          Pode gerar direto sem digitar nada — a IAra usa Base + Referência como contexto. Use a observação para refinar pontualmente.
        </p>
      </div>

      {videoType === 'cut' && (
        <GuestPhotoUploader
          videoId={videoId}
          currentUrl={guestPhotoUrl ?? undefined}
          onChange={onGuestPhotoChange}
        />
      )}

      <Button
        onClick={handleGenerate}
        disabled={isGenerating}
        data-testid="generate-thumbnail-button"
        className="self-start"
      >
        {isGenerating ? (
          <>
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            {spinnerText}
          </>
        ) : (
          <>
            <Sparkles className="h-4 w-4 mr-2" />
            Gerar Thumbnail
          </>
        )}
      </Button>

      {isGenerating && (
        <p className="text-xs text-muted-foreground" data-testid="thumbnail-elapsed">
          Tempo decorrido: {elapsedSeconds}s
        </p>
      )}

      {error && (
        <div
          className="flex items-start gap-2 rounded-md border border-destructive/50 bg-destructive/10 p-2 text-xs text-destructive"
          data-testid="thumbnail-error"
        >
          <AlertTriangleIcon className="h-4 w-4 mt-0.5 shrink-0" />
          <span>{error}</span>
        </div>
      )}
    </div>
  )
}


interface SelectedThumbnailSummaryProps {
  selectedThumbnailUrl?: string
  /** Click na imagem abre o lightbox em tamanho real para avaliação. */
  onPreview?: (url: string) => void
}

function SelectedThumbnailSummary({ selectedThumbnailUrl, onPreview }: SelectedThumbnailSummaryProps) {
  return (
    <div className="rounded-md border bg-card p-4" data-testid="selected-summary">
      <p className="text-sm font-medium mb-2">Thumbnail selecionada</p>
      {selectedThumbnailUrl ? (
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={() => onPreview?.(selectedThumbnailUrl)}
            data-testid="selected-preview-button"
            className="cursor-zoom-in rounded focus:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            aria-label="Ver thumbnail selecionada em tamanho real"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={selectedThumbnailUrl}
              alt="Thumbnail selecionada"
              className="h-24 w-auto rounded border bg-muted object-cover"
            />
          </button>
          <p className="text-xs text-muted-foreground">
            Pronta para publicar. Clique na imagem para ver em tamanho real.
          </p>
        </div>
      ) : (
        <p className="text-xs text-muted-foreground">
          Nenhuma thumbnail selecionada ainda. Use um dos dois caminhos acima.
        </p>
      )}
    </div>
  )
}
