'use client'

import { useState } from 'react'
import { ArrowRightIcon, CheckCircleIcon, ListOrderedIcon, RefreshCwIcon, AlertTriangleIcon, Loader2Icon } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { getNextPhaseName } from '@/lib/wizard'
import type { UseWizardReturn } from '@/hooks/use-wizard'
import type { Video } from '@/types/video'
import type { Phase4Response } from '@/lib/llm/types'

import { ClickableTimestamp } from './clickable-timestamp'
import { ProcessingSpinner } from '../processing-spinner'

interface Phase4ChaptersProps {
  wizard: UseWizardReturn
  video: Video
  /** Result from LLM processing (null while processing or if error) */
  chaptersResult: Phase4Response | null
  /** Error message if processing failed */
  error?: string | null
  /** Callback to retry processing after error */
  onRetry?: () => void
  className?: string
}

/**
 * Phase 4: Chapters - Immutable (Type 2)
 *
 * Displays chapter suggestions generated by LLM.
 * Chapters are divided by topic/subject with timestamps.
 *
 * Key features:
 * - Auto-processes on phase entry
 * - Timestamps seek to exact position (NO context offset for chapters)
 * - First chapter always at 00:00
 * - Requires producer approval before advancing
 * - Type 2: Once processed, cannot be reprocessed
 *
 * @see processamento_video.md - Fase 4 - Capítulos
 * @pattern TIMESTAMP_NO_OFFSET_FOR_CHAPTERS - Chapters seek to exact timestamp
 */
export function Phase4Chapters({
  wizard,
  video,
  chaptersResult,
  error,
  onRetry,
  className,
}: Phase4ChaptersProps) {
  const chapters = chaptersResult?.chapters ?? []
  const hasChapters = chapters.length > 0
  const hasError = !!error

  // Check if first chapter starts at 00:00 (YouTube requirement)
  const firstChapterIsZero = chapters[0]?.timestamp === '00:00'
  const hasFirstChapterWarning = hasChapters && !firstChapterIsZero

  // State for confirmation dialog
  const [showApprovalDialog, setShowApprovalDialog] = useState(false)

  // State for advancing to next phase (prevents double clicks)
  const [isAdvancing, setIsAdvancing] = useState(false)

  // Check if can advance: result must exist with chapters
  const canAdvance = chaptersResult !== null && hasChapters && !hasError && !isAdvancing

  const handleAdvanceClick = () => {
    if (!canAdvance) return
    // Always show approval dialog for chapters
    setShowApprovalDialog(true)
  }

  const handleConfirmAdvance = () => {
    setShowApprovalDialog(false)
    setIsAdvancing(true)
    wizard.completePhaseAndAdvance(4, chaptersResult)
  }

  const videoId = video.id

  return (
    <div className={className}>
      <div className="space-y-4">
        {/* Error state with retry button */}
        {hasError && (
          <Card className="border-destructive">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-destructive">Erro na Geração de Capítulos</CardTitle>
              <CardDescription>
                Não foi possível gerar os capítulos automaticamente.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6">
                <AlertTriangleIcon className="size-12 text-destructive" />
                <p className="text-sm text-muted-foreground text-center">{error}</p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Loading state when no result yet */}
        {!chaptersResult && !hasError && (
          <ProcessingSpinner text="Gerando capítulos automaticamente..." />
        )}

        {/* Chapters list */}
        {chaptersResult && hasChapters && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <ListOrderedIcon className="size-4" />
                Capítulos Sugeridos
              </CardTitle>
              <CardDescription>
                Clique em um timestamp para ir ao ponto do vídeo.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-2">
              {/* Warning if first chapter doesn't start at 00:00 */}
              {hasFirstChapterWarning && (
                <div className="flex items-center gap-2 p-3 mb-2 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-md">
                  <AlertTriangleIcon className="size-4 text-amber-600 shrink-0" />
                  <p className="text-sm text-amber-700 dark:text-amber-400">
                    O primeiro capítulo deve começar em 00:00 para o YouTube aceitar.
                  </p>
                </div>
              )}
              {chapters.map((chapter, index) => (
                <div
                  key={`${chapter.timestamp}-${index}`}
                  className="flex items-center gap-3 py-2 border-b last:border-b-0"
                >
                  <ClickableTimestamp
                    videoId={videoId}
                    timestamp={chapter.timestamp}
                    className="shrink-0 font-mono"
                    applyContextOffset={false}
                  />
                  <span className="text-sm">{chapter.title}</span>
                </div>
              ))}
            </CardContent>
          </Card>
        )}

        {/* Empty state (edge case - LLM returned no chapters) */}
        {chaptersResult && !hasChapters && !hasError && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Capítulos</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6 text-muted-foreground">
                <AlertTriangleIcon className="size-12 text-amber-500" />
                <p className="text-sm text-center">
                  Não foi possível identificar capítulos no conteúdo.
                </p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Advance button */}
        <div className="flex justify-end pt-4">
          <Button
            onClick={handleAdvanceClick}
            disabled={!canAdvance}
          >
            {isAdvancing ? (
              <>
                Avançando...
                <Loader2Icon className="size-4 ml-2 animate-spin" />
              </>
            ) : (
              <>
                Avançar para {getNextPhaseName(4)}
                <ArrowRightIcon className="size-4 ml-2" />
              </>
            )}
          </Button>
        </div>

        {/* Approval confirmation dialog */}
        <AlertDialog open={showApprovalDialog} onOpenChange={setShowApprovalDialog}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle className="flex items-center gap-2">
                <CheckCircleIcon className="size-5 text-primary" />
                Aprova os capítulos?
              </AlertDialogTitle>
              <AlertDialogDescription>
                {chapters.length === 1
                  ? 'Foi gerado 1 capítulo para o vídeo.'
                  : `Foram gerados ${chapters.length} capítulos para o vídeo.`
                }
                {' '}Os capítulos serão incluídos na descrição do YouTube.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Não, revisar</AlertDialogCancel>
              <AlertDialogAction onClick={handleConfirmAdvance}>
                Sim, aprovar
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </div>
  )
}
