'use client'

import { useState, useEffect, useRef } from 'react'
import {
  ArrowRightIcon,
  CheckCircleIcon,
  RefreshCwIcon,
  AlertTriangleIcon,
  SparklesIcon,
  Loader2Icon,
} from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { EditableText } from '@/components/ui/editable-text'
import { Label } from '@/components/ui/label'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Textarea } from '@/components/ui/textarea'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import type { UseWizardReturn } from '@/hooks/use-wizard'
import type { Video } from '@/types/video'
import type { Phase5Response } from '@/lib/llm/types'

import { getNextPhaseNameForType } from '@/lib/wizard'

import { ProcessingSpinner } from '../processing-spinner'

interface Phase5TitleProps {
  wizard: UseWizardReturn
  video: Video
  /** Result from LLM processing (null while processing or if error) */
  titlesResult: Phase5Response | null
  /** Error message if processing failed */
  error?: string | null
  /** Callback to retry processing after error */
  onRetry?: () => void
  /** Callback when revalidation is requested with additional context */
  onRevalidate?: (additionalContext: string) => void
  /** Callback when title is selected */
  onTitleSelect?: (title: string) => void
  /** Callback when a suggested title is edited inline */
  onSuggestedTitleEdit?: (index: number, newTitle: string) => Promise<void>
  className?: string
}

const MAX_ADDITIONAL_CONTEXT_CHARS = 200

/**
 * Phase 5: Title - Reprocessable (Type 1)
 *
 * Displays 5 title suggestions generated by LLM for user selection.
 *
 * Key features:
 * - Auto-processes on phase entry
 * - Radio buttons for title selection
 * - Additional context input for revalidation
 * - Revalidar button with confirmation dialog
 * - Type 1: Can be reprocessed multiple times
 * - Revalidation marks phases 6 and 7 with needsRevalidation
 *
 * @see processamento_video.md - Fase 5 - Titulo
 */
export function Phase5Title({
  wizard,
  video,
  titlesResult,
  error,
  onRetry,
  onRevalidate,
  onTitleSelect,
  onSuggestedTitleEdit,
  className,
}: Phase5TitleProps) {
  const titles = titlesResult?.titles ?? []
  const hasTitles = titles.length > 0
  const hasError = !!error

  // State for tracking locally edited titles (index -> edited value)
  const [editedTitles, setEditedTitles] = useState<Record<number, string>>({})

  // Get display title (edited or original)
  const getDisplayTitle = (index: number) => editedTitles[index] ?? titles[index]

  // Selected title state - initialize from video.title if it exists in the current titles list
  const getInitialTitle = () => {
    if (video.title && titles.includes(video.title)) {
      return video.title
    }
    return ''
  }
  const getInitialIndex = () => {
    if (video.title) {
      const idx = titles.indexOf(video.title)
      if (idx >= 0) return idx
    }
    return -1
  }
  const [selectedTitle, setSelectedTitle] = useState<string>(getInitialTitle())
  const [selectedIndex, setSelectedIndex] = useState<number>(getInitialIndex())

  // Track previous titles to detect when new suggestions arrive
  const prevTitlesRef = useRef<string[] | null>(null)

  // Reset state only when titles array actually changes (new LLM response)
  useEffect(() => {
    const currentTitles = titlesResult?.titles
    const prevTitles = prevTitlesRef.current

    // Check if titles array actually changed (not just a re-render)
    const titlesChanged = currentTitles && (
      !prevTitles ||
      prevTitles.length !== currentTitles.length ||
      prevTitles.some((t, i) => t !== currentTitles[i])
    )

    if (titlesChanged) {
      // Clear edited titles when new suggestions arrive
      setEditedTitles({})
      // Reset selection if current selection is not in new list
      if (selectedTitle && !currentTitles.includes(selectedTitle)) {
        setSelectedTitle('')
        setSelectedIndex(-1)
      }
    }

    // Update ref for next comparison
    prevTitlesRef.current = currentTitles ?? null
  }, [titlesResult?.titles, selectedTitle])

  // Additional context for revalidation
  const [additionalContext, setAdditionalContext] = useState('')

  // State for revalidation confirmation dialog
  const [showRevalidateDialog, setShowRevalidateDialog] = useState(false)

  // State for advancing to next phase (prevents double clicks)
  const [isAdvancing, setIsAdvancing] = useState(false)

  // State for advance confirmation (not needed for Phase 5, but keeping pattern)
  const canAdvance = titlesResult !== null && hasTitles && !!selectedTitle && !hasError && !isAdvancing

  const handleTitleSelect = (index: number) => {
    const displayTitle = getDisplayTitle(index)
    setSelectedIndex(index)
    setSelectedTitle(displayTitle)
    onTitleSelect?.(displayTitle)
  }

  // Handle editing a suggested title - optimistic update then persist
  const handleSuggestedTitleEdit = async (index: number, newValue: string) => {
    // Update local state FIRST (optimistic update for immediate UI feedback)
    setEditedTitles(prev => ({ ...prev, [index]: newValue }))

    // If this was the selected title, update selection too
    if (selectedIndex === index) {
      setSelectedTitle(newValue)
      onTitleSelect?.(newValue)
    }

    // Then persist to Firestore via callback
    await onSuggestedTitleEdit?.(index, newValue)
  }

  const handleAdvanceClick = () => {
    if (!canAdvance) return
    setIsAdvancing(true)
    wizard.completePhaseAndAdvance(5, { selectedTitle })
  }

  const handleRevalidateClick = () => {
    setShowRevalidateDialog(true)
  }

  const handleConfirmRevalidate = () => {
    setShowRevalidateDialog(false)
    onRevalidate?.(additionalContext)
  }

  const remainingChars = MAX_ADDITIONAL_CONTEXT_CHARS - additionalContext.length

  return (
    <div className={className}>
      <div className="space-y-4">
        {/* Error state with retry button */}
        {hasError && (
          <Card className="border-destructive">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-destructive">
                Erro na Geracao de Titulos
              </CardTitle>
              <CardDescription>
                Nao foi possivel gerar os titulos automaticamente.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6">
                <AlertTriangleIcon className="size-12 text-destructive" />
                <p className="text-sm text-muted-foreground text-center">{error}</p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Loading state when no result yet */}
        {!titlesResult && !hasError && (
          <ProcessingSpinner text="Gerando sugestões de título..." />
        )}

        {/* Titles list with radio buttons */}
        {titlesResult && hasTitles && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <SparklesIcon className="size-4" />
                Sugestoes de Titulo
              </CardTitle>
              <CardDescription>
                Selecione o melhor titulo para o video.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <RadioGroup
                value={selectedIndex >= 0 ? String(selectedIndex) : ''}
                onValueChange={(value) => handleTitleSelect(parseInt(value, 10))}
                className="space-y-3"
              >
                {titles.map((title, index) => {
                  const displayTitle = getDisplayTitle(index)
                  return (
                    <div
                      key={`title-${index}`}
                      className="flex items-start space-x-3 p-3 rounded-md border hover:bg-accent/50 transition-colors"
                    >
                      <RadioGroupItem
                        value={String(index)}
                        id={`title-${index}`}
                        aria-label={displayTitle}
                        className="mt-0.5"
                      />
                      <div className="flex-1">
                        <EditableText
                          value={displayTitle}
                          onSave={(newValue) => handleSuggestedTitleEdit(index, newValue)}
                          textClassName="text-sm leading-relaxed cursor-text"
                          placeholder="Titulo vazio"
                        />
                      </div>
                    </div>
                  )
                })}
              </RadioGroup>

              {/* Additional context input for revalidation */}
              <div className="pt-4 border-t">
                <div className="space-y-2">
                  <Label htmlFor="additional-context" className="text-sm font-medium">
                    Dica para novos titulos (opcional)
                  </Label>
                  <Textarea
                    id="additional-context"
                    placeholder="Ex: Foque mais no convidado principal, use palavras mais chamativas..."
                    value={additionalContext}
                    onChange={(e) => setAdditionalContext(e.target.value)}
                    maxLength={MAX_ADDITIONAL_CONTEXT_CHARS}
                    className="min-h-[80px] resize-none"
                  />
                  <div className="flex justify-between items-center text-xs text-muted-foreground">
                    <span>Use para gerar novos titulos com contexto adicional</span>
                    <span className={remainingChars < 20 ? 'text-amber-500' : ''}>
                      {remainingChars} caracteres restantes
                    </span>
                  </div>
                </div>

                {/* Revalidar button */}
                <div className="mt-3">
                  <Button
                    variant="outline"
                    onClick={handleRevalidateClick}
                    disabled={!onRevalidate}
                  >
                    <RefreshCwIcon className="size-4 mr-2" />
                    Gerar novos titulos
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Empty state (edge case - LLM returned no titles) */}
        {titlesResult && !hasTitles && !hasError && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Titulos</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6 text-muted-foreground">
                <AlertTriangleIcon className="size-12 text-amber-500" />
                <p className="text-sm text-center">
                  Nao foi possivel gerar sugestoes de titulo.
                </p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Advance button */}
        <div className="flex justify-end pt-4">
          <Button onClick={handleAdvanceClick} disabled={!canAdvance}>
            {isAdvancing ? (
              <>
                Avançando...
                <Loader2Icon className="size-4 ml-2 animate-spin" />
              </>
            ) : (
              <>
                Avançar para {getNextPhaseNameForType(5, video.videoType)}
                <ArrowRightIcon className="size-4 ml-2" />
              </>
            )}
          </Button>
        </div>

        {/* Revalidation confirmation dialog */}
        <AlertDialog open={showRevalidateDialog} onOpenChange={setShowRevalidateDialog}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle className="flex items-center gap-2">
                <RefreshCwIcon className="size-5 text-primary" />
                Gerar novos titulos?
              </AlertDialogTitle>
              <AlertDialogDescription>
                Ao gerar novos titulos, as fases seguintes (Descricao e Tags) serao marcadas
                para revalidacao. Os dados existentes serao preservados, mas voce podera
                optar por revalidar quando chegar nessas fases.
                {additionalContext && (
                  <span className="block mt-2 text-foreground">
                    <strong>Sua dica:</strong> {additionalContext}
                  </span>
                )}
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancelar</AlertDialogCancel>
              <AlertDialogAction onClick={handleConfirmRevalidate}>
                <CheckCircleIcon className="size-4 mr-2" />
                Sim, gerar novos
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </div>
  )
}
