'use client'

import { useState, useEffect } from 'react'
import {
  ArrowRightIcon,
  CheckCircleIcon,
  RefreshCwIcon,
  AlertTriangleIcon,
  SparklesIcon,
  Loader2Icon,
} from 'lucide-react'

import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Textarea } from '@/components/ui/textarea'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import type { UseWizardReturn } from '@/hooks/use-wizard'
import type { Video } from '@/types/video'
import type { Phase5BResponse } from '@/lib/llm/types'

import { ProcessingSpinner } from '../processing-spinner'

interface Phase5BShortTitleProps {
  wizard: UseWizardReturn
  video: Video
  /** Result from LLM processing (null while processing or if error) */
  shortTitlesResult: Phase5BResponse | null
  /** Error message if processing failed */
  error?: string | null
  /** Callback to retry processing after error */
  onRetry?: () => void
  /** Callback when revalidation is requested with additional context */
  onRevalidate?: (additionalContext: string) => void
  /** Callback when short title is selected */
  onShortTitleSelect?: (shortTitle: string) => void
  className?: string
}

const MAX_ADDITIONAL_CONTEXT_CHARS = 200

/**
 * Phase 5B: Short Title - Reprocessable (Type 1)
 *
 * Displays 5 short title suggestions generated by LLM for thumbnail selection.
 * Exclusive to cut videos.
 *
 * Key features:
 * - Auto-processes on phase entry
 * - Radio buttons for short title selection
 * - Additional context input for revalidation
 * - Revalidar button with confirmation dialog
 * - Type 1: Can be reprocessed multiple times
 * - Phase 5B is independent (no SEO cascade to phases 6/7)
 *
 * @see Story 4 - Cut Flow (Phase 5B)
 */
export function Phase5BShortTitle({
  wizard,
  video,
  shortTitlesResult,
  error,
  onRetry,
  onRevalidate,
  onShortTitleSelect,
  className,
}: Phase5BShortTitleProps) {
  const shortTitles = shortTitlesResult?.shortTitles ?? []
  const hasShortTitles = shortTitles.length > 0
  const hasError = !!error

  // Selected short title state - initialize from video.shortTitle if it exists in the current list
  const getInitialShortTitle = () => {
    if (video.shortTitle && shortTitles.includes(video.shortTitle)) {
      return video.shortTitle
    }
    return ''
  }
  const [selectedShortTitle, setSelectedShortTitle] = useState<string>(getInitialShortTitle())

  // Reset selected short title when result changes and current selection is not in list
  useEffect(() => {
    if (shortTitlesResult?.shortTitles && shortTitlesResult.shortTitles.length > 0) {
      // If current selection is not in the new list, reset
      if (selectedShortTitle && !shortTitlesResult.shortTitles.includes(selectedShortTitle)) {
        setSelectedShortTitle('')
      }
    }
  }, [shortTitlesResult?.shortTitles, selectedShortTitle])

  // Additional context for revalidation
  const [additionalContext, setAdditionalContext] = useState('')

  // State for revalidation confirmation dialog
  const [showRevalidateDialog, setShowRevalidateDialog] = useState(false)

  // State for advancing to next phase (prevents double clicks)
  const [isAdvancing, setIsAdvancing] = useState(false)

  const canAdvance = shortTitlesResult !== null && hasShortTitles && !!selectedShortTitle && !hasError && !isAdvancing

  const handleShortTitleSelect = (shortTitle: string) => {
    setSelectedShortTitle(shortTitle)
    onShortTitleSelect?.(shortTitle)
  }

  const handleAdvanceClick = () => {
    if (!canAdvance) return
    setIsAdvancing(true)
    // Phase 5B advances to phase 6 (Description)
    // The selectedShortTitle is already persisted via onShortTitleSelect callback
    // Use completePhaseAndAdvance to properly mark phase 5B as complete and navigate.
    // Note: Phase 5B completion is tracked via video.shortTitle in Firestore,
    // not in the wizard phases record (which only has phases 1-8).
    wizard.completePhaseAndAdvance('5B', { shortTitle: selectedShortTitle })
  }

  const handleRevalidateClick = () => {
    setShowRevalidateDialog(true)
  }

  const handleConfirmRevalidate = () => {
    setShowRevalidateDialog(false)
    onRevalidate?.(additionalContext)
  }

  const remainingChars = MAX_ADDITIONAL_CONTEXT_CHARS - additionalContext.length

  return (
    <div className={className}>
      <div className="space-y-4">
        {/* Error state with retry button */}
        {hasError && (
          <Card className="border-destructive">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-destructive">
                Erro na Geracao de Titulos Curtos
              </CardTitle>
              <CardDescription>
                Nao foi possivel gerar os titulos curtos automaticamente.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6">
                <AlertTriangleIcon className="size-12 text-destructive" />
                <p className="text-sm text-muted-foreground text-center">{error}</p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Loading state when no result yet */}
        {!shortTitlesResult && !hasError && (
          <ProcessingSpinner text="Gerando sugestões de título curto para thumbnail..." />
        )}

        {/* Short titles list with radio buttons */}
        {shortTitlesResult && hasShortTitles && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <SparklesIcon className="size-4" />
                Sugestoes de Titulo Curto
              </CardTitle>
              <CardDescription>
                Selecione o melhor titulo curto para a thumbnail do corte.
                Titulos curtos sao mais impactantes e funcionam melhor em miniaturas.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <RadioGroup
                value={selectedShortTitle}
                onValueChange={handleShortTitleSelect}
                className="space-y-3"
              >
                {shortTitles.map((shortTitle, index) => (
                  <div
                    key={`short-title-${index}`}
                    className="flex items-start space-x-3 p-3 rounded-md border hover:bg-accent/50 transition-colors"
                  >
                    <RadioGroupItem
                      value={shortTitle}
                      id={`short-title-${index}`}
                      className="mt-0.5"
                    />
                    <Label
                      htmlFor={`short-title-${index}`}
                      className="flex-1 cursor-pointer text-sm leading-relaxed font-medium"
                    >
                      {shortTitle}
                    </Label>
                    <span className={cn(
                      "text-xs",
                      shortTitle.length >= 15 && shortTitle.length <= 35
                        ? "text-green-500"
                        : "text-amber-500"
                    )}>
                      {shortTitle.length} chars
                    </span>
                  </div>
                ))}
              </RadioGroup>

              {/* Additional context input for revalidation */}
              <div className="pt-4 border-t">
                <div className="space-y-2">
                  <Label htmlFor="additional-context-5b" className="text-sm font-medium">
                    Dica para novos titulos curtos (opcional)
                  </Label>
                  <Textarea
                    id="additional-context-5b"
                    placeholder="Ex: Foque mais no momento de impacto, use uma pergunta provocativa..."
                    value={additionalContext}
                    onChange={(e) => setAdditionalContext(e.target.value)}
                    maxLength={MAX_ADDITIONAL_CONTEXT_CHARS}
                    className="min-h-[80px] resize-none"
                  />
                  <div className="flex justify-between items-center text-xs text-muted-foreground">
                    <span>Use para gerar novos titulos curtos com contexto adicional</span>
                    <span className={remainingChars < 20 ? 'text-amber-500' : ''}>
                      {remainingChars} caracteres restantes
                    </span>
                  </div>
                </div>

                {/* Revalidar button */}
                <div className="mt-3">
                  <Button
                    variant="outline"
                    onClick={handleRevalidateClick}
                    disabled={!onRevalidate}
                  >
                    <RefreshCwIcon className="size-4 mr-2" />
                    Gerar novos titulos curtos
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Empty state (edge case - LLM returned no short titles) */}
        {shortTitlesResult && !hasShortTitles && !hasError && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Titulos Curtos</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6 text-muted-foreground">
                <AlertTriangleIcon className="size-12 text-amber-500" />
                <p className="text-sm text-center">
                  Nao foi possivel gerar sugestoes de titulo curto.
                </p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Advance button */}
        <div className="flex justify-end pt-4">
          <Button onClick={handleAdvanceClick} disabled={!canAdvance}>
            {isAdvancing ? (
              <>
                Avançando...
                <Loader2Icon className="size-4 ml-2 animate-spin" />
              </>
            ) : (
              <>
                Avançar para Descrição
                <ArrowRightIcon className="size-4 ml-2" />
              </>
            )}
          </Button>
        </div>

        {/* Revalidation confirmation dialog */}
        <AlertDialog open={showRevalidateDialog} onOpenChange={setShowRevalidateDialog}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle className="flex items-center gap-2">
                <RefreshCwIcon className="size-5 text-primary" />
                Gerar novos titulos curtos?
              </AlertDialogTitle>
              <AlertDialogDescription>
                Os titulos curtos atuais serao substituidos por novas sugestoes.
                Isso nao afeta as fases seguintes (Descricao e Tags).
                {additionalContext && (
                  <span className="block mt-2 text-foreground">
                    <strong>Sua dica:</strong> {additionalContext}
                  </span>
                )}
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancelar</AlertDialogCancel>
              <AlertDialogAction onClick={handleConfirmRevalidate}>
                <CheckCircleIcon className="size-4 mr-2" />
                Sim, gerar novos
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </div>
  )
}
