'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import {
  ArrowRightIcon,
  RefreshCwIcon,
  AlertTriangleIcon,
  TagIcon,
  XIcon,
  PlusIcon,
  Loader2Icon,
} from 'lucide-react'

import { log } from '@/lib/logger'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import type { UseWizardReturn } from '@/hooks/use-wizard'
import type { Video } from '@/types/video'
import type { Phase7Response } from '@/lib/llm/types'

import { getNextPhaseNameForType } from '@/lib/wizard'

import { ProcessingSpinner } from '../processing-spinner'

interface Phase7TagsProps {
  wizard: UseWizardReturn
  video: Video
  /** Result from LLM processing (null while processing or if error) */
  tagsResult: Phase7Response | null
  /** Error message if processing failed */
  error?: string | null
  /** Callback to retry processing after error */
  onRetry?: () => void
  /** Callback when revalidation is requested with additional context */
  onRevalidate?: (additionalContext: string) => void
  /** Callback when tags are changed. Returns promise for advance sync. */
  onTagsChange?: (tags: string[]) => Promise<void>
  /**
   * Optional podcast features (Epic 22 / Story 22.3a). When
   * `thumbnailGeneration` is on, advancing from this phase routes to
   * 'THUMB' before Publicar (8) for episode/cut. Without this prop the
   * state machine falls back to the legacy 7 → 8 sequence and SKIPS the
   * Thumbnail phase silently.
   */
  features?: { thumbnailGeneration?: boolean }
  className?: string
}

// =============================================================================
// Topics sub-section (Story 20.1)
// =============================================================================

interface TopicsSectionProps {
  videoId: string
  initialTopics: string[]
}

function TopicsSection({ videoId, initialTopics }: TopicsSectionProps) {
  const [topics, setTopics] = useState<string[]>(initialTopics)
  const [availableTopics, setAvailableTopics] = useState<string[]>([])
  const [isGenerating, setIsGenerating] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [hasGenerated, setHasGenerated] = useState(initialTopics.length > 0)
  const [topicError, setTopicError] = useState<string | null>(null)
  const hasAutoGeneratedRef = useRef(false)

  // Fetch available topics on mount
  useEffect(() => {
    fetch('/api/topics')
      .then((res) => res.json())
      .then((data) => {
        setAvailableTopics(data.data?.topics ?? [])
      })
      .catch(() => {
        // Silently ignore — topics section won't show dropdown
      })
  }, [])

  // Auto-generate topics when component mounts.
  // On remount after tag regeneration (key changes), ref resets and auto-generate fires.
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return
    hasAutoGeneratedRef.current = true
    handleGenerate()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleGenerate = async () => {
    setIsGenerating(true)
    setTopicError(null)

    try {
      const response = await fetch(`/api/videos/${videoId}/topics`, {
        method: 'POST',
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        throw new Error(errorData.error?.message || 'Erro ao categorizar tópicos')
      }

      const result = await response.json()
      const newTopics = result.data?.topics ?? []
      setTopics(newTopics)
      setHasGenerated(true)
    } catch (err) {
      setTopicError(err instanceof Error ? err.message : 'Erro desconhecido')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleRemoveTopic = async (topicToRemove: string) => {
    if (isSaving) return
    const newTopics = topics.filter((t) => t !== topicToRemove)
    setTopics(newTopics)
    setIsSaving(true)
    try {
      await fetch(`/api/videos/${videoId}/topics`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topics: newTopics }),
      })
    } catch {
      setTopics(topics) // rollback
    } finally {
      setIsSaving(false)
    }
  }

  const handleAddTopic = async (topicToAdd: string) => {
    if (isSaving || topics.includes(topicToAdd)) return
    const newTopics = [...topics, topicToAdd]
    setTopics(newTopics)
    setIsSaving(true)
    try {
      await fetch(`/api/videos/${videoId}/topics`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topics: newTopics }),
      })
    } catch {
      setTopics(topics) // rollback
    } finally {
      setIsSaving(false)
    }
  }

  const unusedTopics = availableTopics.filter((t) => !topics.includes(t))

  if (availableTopics.length === 0 && !isGenerating && !hasGenerated) {
    return null // No topics configured — silently skip
  }

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base flex items-center gap-2">
          <TagIcon className="size-4" />
          Tópicos do Episódio
        </CardTitle>
        <CardDescription>
          Tópicos do catálogo do podcast atribuídos a este vídeo.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isGenerating && (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2Icon className="size-4 animate-spin" />
            Categorizando tópicos via IA...
          </div>
        )}

        {topicError && (
          <div className="text-sm text-destructive flex items-center gap-2">
            <AlertTriangleIcon className="size-4" />
            {topicError}
          </div>
        )}

        {/* Selected topics as badges */}
        {!isGenerating && (
          <div className="flex flex-wrap gap-2">
            {topics.map((topic) => (
              <Badge
                key={topic}
                variant="default"
                className={`flex items-center gap-1 px-3 py-1 ${isSaving ? 'opacity-70' : ''}`}
              >
                {topic}
                <button
                  type="button"
                  onClick={() => handleRemoveTopic(topic)}
                  disabled={isSaving}
                  className="ml-1 hover:text-destructive-foreground/70 transition-colors disabled:opacity-50"
                  aria-label={`Remover tópico ${topic}`}
                >
                  <XIcon className="size-3" />
                </button>
              </Badge>
            ))}
            {topics.length === 0 && hasGenerated && (
              <p className="text-sm text-muted-foreground">Nenhum tópico atribuído.</p>
            )}
          </div>
        )}

        {/* Dropdown to add topics */}
        {!isGenerating && unusedTopics.length > 0 && (
          <div className="flex flex-wrap gap-1.5">
            {unusedTopics.map((topic) => (
              <Badge
                key={topic}
                variant="outline"
                className="cursor-pointer hover:bg-accent transition-colors"
                onClick={() => handleAddTopic(topic)}
              >
                <PlusIcon className="size-3 mr-1" />
                {topic}
              </Badge>
            ))}
          </div>
        )}

        {/* Regenerate button */}
        {hasGenerated && !isGenerating && (
          <div className="pt-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleGenerate}
              disabled={isGenerating}
            >
              <RefreshCwIcon className="size-4 mr-2" />
              Recategorizar tópicos
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

const MAX_TOTAL_CHARS = 500
const MAX_ADDITIONAL_CONTEXT_CHARS = 200

/**
 * Phase 7: Tags - Reprocessable (Type 1)
 *
 * Displays SEO-optimized tags generated by LLM for user editing.
 *
 * Key features:
 * - Auto-processes on phase entry
 * - Tags displayed as removable chips/badges
 * - Can add new tags manually
 * - 500 character limit (YouTube requirement)
 * - Additional context input for revalidation
 * - Revalidar button (no confirmation needed - last LLM phase)
 * - Type 1: Can be reprocessed multiple times
 *
 * @see processamento_video.md - Fase 7 - Tags
 */
export function Phase7Tags({
  wizard,
  video,
  tagsResult,
  error,
  onRetry,
  onRevalidate,
  onTagsChange,
  features,
  className,
}: Phase7TagsProps) {
  const hasResult = tagsResult !== null
  const hasError = !!error

  // Tags state - initialize from result or video.tags
  const [tags, setTags] = useState<string[]>(tagsResult?.tags ?? video.tags ?? [])

  // New tag input state
  const [newTag, setNewTag] = useState('')

  // State for tracking save operations (prevents race conditions)
  const [isSaving, setIsSaving] = useState(false)

  // Ref to block external sync while local editing is in progress
  const isLocalEditingRef = useRef(false)

  // Update tags when result changes or when video.tags changes externally
  // BUT only if we're not currently editing locally (prevents race condition)
  useEffect(() => {
    // Skip sync if local editing is in progress to prevent overwriting user changes
    if (isLocalEditingRef.current) {
      return
    }

    if (tagsResult?.tags) {
      setTags(tagsResult.tags)
    } else if (video.tags && video.tags.length > 0) {
      // Sync from video.tags if no tagsResult yet (e.g., returning to phase)
      setTags(video.tags)
    }
  }, [tagsResult?.tags, video.tags])

  // Additional context for revalidation
  const [additionalContext, setAdditionalContext] = useState('')

  // State for advancing to next phase (prevents double clicks)
  const [isAdvancing, setIsAdvancing] = useState(false)

  // Calculate total characters used
  const totalChars = tags.join(',').length
  const remainingChars = MAX_TOTAL_CHARS - totalChars
  const remainingContextChars = MAX_ADDITIONAL_CONTEXT_CHARS - additionalContext.length

  // Check if can advance: result must exist and at least 1 tag
  const canAdvance = hasResult && tags.length > 0 && !hasError && !isAdvancing

  // Handle adding a new tag
  const handleAddTag = useCallback(async () => {
    const trimmedTag = newTag.trim()
    if (!trimmedTag || isSaving) return

    // Check if tag already exists
    if (tags.includes(trimmedTag)) {
      setNewTag('')
      return
    }

    // Check if adding would exceed limit
    const newTotalChars = totalChars + (totalChars > 0 ? 1 : 0) + trimmedTag.length
    if (newTotalChars > MAX_TOTAL_CHARS) {
      return
    }

    const newTags = [...tags, trimmedTag]

    // Optimistic update
    setTags(newTags)
    setNewTag('')

    // Block external sync and persist
    isLocalEditingRef.current = true
    setIsSaving(true)

    try {
      await onTagsChange?.(newTags)
      log('INFO', 'Tag added successfully', { tag: trimmedTag })
    } catch (error) {
      // Rollback on error
      setTags(tags)
      log('ERROR', 'Failed to add tag', {
        tag: trimmedTag,
        error: error instanceof Error ? error.message : 'Unknown error',
      })
    } finally {
      setIsSaving(false)
      // Release sync lock after a short delay to ensure Firestore has updated
      setTimeout(() => {
        isLocalEditingRef.current = false
      }, 500)
    }
  }, [newTag, tags, totalChars, onTagsChange, isSaving])

  // Handle removing a tag
  const handleRemoveTag = useCallback(
    async (tagToRemove: string) => {
      if (isSaving) return

      const newTags = tags.filter((tag) => tag !== tagToRemove)

      // Optimistic update
      setTags(newTags)

      // Block external sync and persist
      isLocalEditingRef.current = true
      setIsSaving(true)

      try {
        await onTagsChange?.(newTags)
        log('INFO', 'Tag removed successfully', { tag: tagToRemove })
      } catch (error) {
        // Rollback on error - restore the removed tag
        setTags(tags)
        log('ERROR', 'Failed to remove tag', {
          tag: tagToRemove,
          error: error instanceof Error ? error.message : 'Unknown error',
        })
      } finally {
        setIsSaving(false)
        // Release sync lock after a short delay to ensure Firestore has updated
        setTimeout(() => {
          isLocalEditingRef.current = false
        }, 500)
      }
    },
    [tags, onTagsChange, isSaving]
  )

  // Handle Enter key in new tag input
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter') {
        e.preventDefault()
        handleAddTag()
      }
    },
    [handleAddTag]
  )

  const handleAdvanceClick = async () => {
    if (!canAdvance) return
    setIsAdvancing(true)
    // Always save tags before advancing (even if user didn't edit)
    try {
      await onTagsChange?.(tags)
    } catch (error) {
      // Log error but don't block advance - user can still proceed
      log('WARN', 'Failed to save tags on advance, continuing anyway', {
        error: error instanceof Error ? error.message : 'Unknown error',
      })
    }
    wizard.completePhaseAndAdvance('tags', { tags }, features)
  }

  const handleRevalidateClick = () => {
    // No confirmation needed for Phase 7 (last LLM phase, no subsequent phases to mark)
    onRevalidate?.(additionalContext)
  }

  return (
    <div className={className}>
      <div className="space-y-4">
        {/* Error state with retry button */}
        {hasError && (
          <Card className="border-destructive">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-destructive">
                Erro na Geracao de Tags
              </CardTitle>
              <CardDescription>
                Nao foi possivel gerar as tags automaticamente.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6">
                <AlertTriangleIcon className="size-12 text-destructive" />
                <p className="text-sm text-muted-foreground text-center">{error}</p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Loading state when no result yet */}
        {!tagsResult && !hasError && (
          <ProcessingSpinner text="Gerando tags otimizadas para SEO..." />
        )}

        {/* Tags list */}
        {tagsResult && !hasError && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <TagIcon className="size-4" />
                Tags Geradas
              </CardTitle>
              <CardDescription>
                Adicione ou remova tags conforme necessario.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Tags as chips */}
              <div className="flex flex-wrap gap-2">
                {tags.map((tag) => (
                  <Badge
                    key={tag}
                    variant="secondary"
                    className={`flex items-center gap-1 px-3 py-1 ${isSaving ? 'opacity-70' : ''}`}
                  >
                    {tag}
                    <button
                      type="button"
                      onClick={() => handleRemoveTag(tag)}
                      disabled={isSaving}
                      className="ml-1 hover:text-destructive transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                      aria-label={`Remover tag ${tag}`}
                    >
                      <XIcon className="size-3" />
                    </button>
                  </Badge>
                ))}
                {tags.length === 0 && (
                  <p className="text-sm text-muted-foreground">
                    Nenhuma tag adicionada ainda.
                  </p>
                )}
              </div>

              {/* Add new tag input */}
              <div className="flex gap-2">
                <Input
                  placeholder="Adicionar nova tag..."
                  value={newTag}
                  onChange={(e) => setNewTag(e.target.value)}
                  onKeyDown={handleKeyDown}
                  disabled={isSaving}
                  className="flex-1"
                />
                <Button
                  variant="outline"
                  onClick={handleAddTag}
                  disabled={!newTag.trim() || remainingChars < newTag.trim().length + 1 || isSaving}
                >
                  {isSaving ? (
                    <Loader2Icon className="size-4 mr-1 animate-spin" />
                  ) : (
                    <PlusIcon className="size-4 mr-1" />
                  )}
                  Adicionar
                </Button>
              </div>

              {/* Character count */}
              <div className="flex justify-end text-xs text-muted-foreground">
                <span className={remainingChars < 50 ? 'text-amber-500' : ''}>
                  {totalChars}/{MAX_TOTAL_CHARS} caracteres usados
                </span>
              </div>

              {/* Additional context input for revalidation */}
              <div className="pt-4 border-t">
                <div className="space-y-2">
                  <Label htmlFor="additional-context" className="text-sm font-medium">
                    Dica para novas tags (opcional)
                  </Label>
                  <Textarea
                    id="additional-context"
                    placeholder="Ex: Foque mais em termos tecnicos, adicione tags em ingles..."
                    value={additionalContext}
                    onChange={(e) => setAdditionalContext(e.target.value)}
                    maxLength={MAX_ADDITIONAL_CONTEXT_CHARS}
                    className="min-h-[80px] resize-none"
                  />
                  <div className="flex justify-between items-center text-xs text-muted-foreground">
                    <span>Use para gerar novas tags com contexto adicional</span>
                    <span className={remainingContextChars < 20 ? 'text-amber-500' : ''}>
                      {remainingContextChars} caracteres restantes
                    </span>
                  </div>
                </div>

                {/* Revalidar button */}
                <div className="mt-3">
                  <Button
                    variant="outline"
                    onClick={handleRevalidateClick}
                    disabled={!onRevalidate}
                  >
                    <RefreshCwIcon className="size-4 mr-2" />
                    Gerar novas tags
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Topics sub-section (Story 20.1) — key forces remount on tag regeneration (AC7) */}
        {tagsResult && !hasError && (
          <TopicsSection
            key={tagsResult.tags?.join(',') ?? 'init'}
            videoId={video.id}
            initialTopics={video.topics ?? []}
          />
        )}

        {/* Advance button */}
        <div className="flex justify-end pt-4">
          <Button onClick={handleAdvanceClick} disabled={!canAdvance}>
            {isAdvancing ? (
              <>
                Avançando...
                <Loader2Icon className="size-4 ml-2 animate-spin" />
              </>
            ) : (
              <>
                Avançar para {getNextPhaseNameForType('tags', video.videoType, features)}
                <ArrowRightIcon className="size-4 ml-2" />
              </>
            )}
          </Button>
        </div>
      </div>
    </div>
  )
}
