'use client'

import { useState, useEffect } from 'react'
import {
  ArrowRightIcon,
  CheckCircleIcon,
  RefreshCwIcon,
  AlertTriangleIcon,
  SparklesIcon,
  Loader2Icon,
} from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Textarea } from '@/components/ui/textarea'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import type { UseWizardReturn } from '@/hooks/use-wizard'
import type { Video } from '@/types/video'
import type { Phase5Response } from '@/lib/llm/types'

import { getNextPhaseName } from '@/lib/wizard'

import { ProcessingSpinner } from '../processing-spinner'

interface Phase5TitleProps {
  wizard: UseWizardReturn
  video: Video
  /** Result from LLM processing (null while processing or if error) */
  titlesResult: Phase5Response | null
  /** Error message if processing failed */
  error?: string | null
  /** Callback to retry processing after error */
  onRetry?: () => void
  /** Callback when revalidation is requested with additional context */
  onRevalidate?: (additionalContext: string) => void
  /** Callback when title is selected */
  onTitleSelect?: (title: string) => void
  className?: string
}

const MAX_ADDITIONAL_CONTEXT_CHARS = 200

/**
 * Phase 5: Title - Reprocessable (Type 1)
 *
 * Displays 5 title suggestions generated by LLM for user selection.
 *
 * Key features:
 * - Auto-processes on phase entry
 * - Radio buttons for title selection
 * - Additional context input for revalidation
 * - Revalidar button with confirmation dialog
 * - Type 1: Can be reprocessed multiple times
 * - Revalidation marks phases 6 and 7 with needsRevalidation
 *
 * @see processamento_video.md - Fase 5 - Titulo
 */
export function Phase5Title({
  wizard,
  video,
  titlesResult,
  error,
  onRetry,
  onRevalidate,
  onTitleSelect,
  className,
}: Phase5TitleProps) {
  const titles = titlesResult?.titles ?? []
  const hasTitles = titles.length > 0
  const hasError = !!error

  // Selected title state - initialize from video.title if it exists in the current titles list
  const getInitialTitle = () => {
    if (video.title && titles.includes(video.title)) {
      return video.title
    }
    return ''
  }
  const [selectedTitle, setSelectedTitle] = useState<string>(getInitialTitle())

  // Reset selected title when titles result changes and current selection is not in list
  useEffect(() => {
    if (titlesResult?.titles && titlesResult.titles.length > 0) {
      // If current selection is not in the new titles list, reset
      if (selectedTitle && !titlesResult.titles.includes(selectedTitle)) {
        setSelectedTitle('')
      }
    }
  }, [titlesResult?.titles, selectedTitle])

  // Additional context for revalidation
  const [additionalContext, setAdditionalContext] = useState('')

  // State for revalidation confirmation dialog
  const [showRevalidateDialog, setShowRevalidateDialog] = useState(false)

  // State for advancing to next phase (prevents double clicks)
  const [isAdvancing, setIsAdvancing] = useState(false)

  // State for advance confirmation (not needed for Phase 5, but keeping pattern)
  const canAdvance = titlesResult !== null && hasTitles && !!selectedTitle && !hasError && !isAdvancing

  const handleTitleSelect = (title: string) => {
    setSelectedTitle(title)
    onTitleSelect?.(title)
  }

  const handleAdvanceClick = () => {
    if (!canAdvance) return
    setIsAdvancing(true)
    wizard.completePhaseAndAdvance(5, { selectedTitle })
  }

  const handleRevalidateClick = () => {
    setShowRevalidateDialog(true)
  }

  const handleConfirmRevalidate = () => {
    setShowRevalidateDialog(false)
    onRevalidate?.(additionalContext)
  }

  const remainingChars = MAX_ADDITIONAL_CONTEXT_CHARS - additionalContext.length

  return (
    <div className={className}>
      <div className="space-y-4">
        {/* Error state with retry button */}
        {hasError && (
          <Card className="border-destructive">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-destructive">
                Erro na Geracao de Titulos
              </CardTitle>
              <CardDescription>
                Nao foi possivel gerar os titulos automaticamente.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6">
                <AlertTriangleIcon className="size-12 text-destructive" />
                <p className="text-sm text-muted-foreground text-center">{error}</p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Loading state when no result yet */}
        {!titlesResult && !hasError && (
          <ProcessingSpinner text="Gerando sugestões de título..." />
        )}

        {/* Titles list with radio buttons */}
        {titlesResult && hasTitles && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <SparklesIcon className="size-4" />
                Sugestoes de Titulo
              </CardTitle>
              <CardDescription>
                Selecione o melhor titulo para o video.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <RadioGroup
                value={selectedTitle}
                onValueChange={handleTitleSelect}
                className="space-y-3"
              >
                {titles.map((title, index) => (
                  <div
                    key={`title-${index}`}
                    className="flex items-start space-x-3 p-3 rounded-md border hover:bg-accent/50 transition-colors"
                  >
                    <RadioGroupItem
                      value={title}
                      id={`title-${index}`}
                      className="mt-0.5"
                    />
                    <Label
                      htmlFor={`title-${index}`}
                      className="flex-1 cursor-pointer text-sm leading-relaxed"
                    >
                      {title}
                    </Label>
                  </div>
                ))}
              </RadioGroup>

              {/* Additional context input for revalidation */}
              <div className="pt-4 border-t">
                <div className="space-y-2">
                  <Label htmlFor="additional-context" className="text-sm font-medium">
                    Dica para novos titulos (opcional)
                  </Label>
                  <Textarea
                    id="additional-context"
                    placeholder="Ex: Foque mais no convidado principal, use palavras mais chamativas..."
                    value={additionalContext}
                    onChange={(e) => setAdditionalContext(e.target.value)}
                    maxLength={MAX_ADDITIONAL_CONTEXT_CHARS}
                    className="min-h-[80px] resize-none"
                  />
                  <div className="flex justify-between items-center text-xs text-muted-foreground">
                    <span>Use para gerar novos titulos com contexto adicional</span>
                    <span className={remainingChars < 20 ? 'text-amber-500' : ''}>
                      {remainingChars} caracteres restantes
                    </span>
                  </div>
                </div>

                {/* Revalidar button */}
                <div className="mt-3">
                  <Button
                    variant="outline"
                    onClick={handleRevalidateClick}
                    disabled={!onRevalidate}
                  >
                    <RefreshCwIcon className="size-4 mr-2" />
                    Gerar novos titulos
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Empty state (edge case - LLM returned no titles) */}
        {titlesResult && !hasTitles && !hasError && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Titulos</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6 text-muted-foreground">
                <AlertTriangleIcon className="size-12 text-amber-500" />
                <p className="text-sm text-center">
                  Nao foi possivel gerar sugestoes de titulo.
                </p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Advance button */}
        <div className="flex justify-end pt-4">
          <Button onClick={handleAdvanceClick} disabled={!canAdvance}>
            {isAdvancing ? (
              <>
                Avançando...
                <Loader2Icon className="size-4 ml-2 animate-spin" />
              </>
            ) : (
              <>
                Avançar para {getNextPhaseName(5)}
                <ArrowRightIcon className="size-4 ml-2" />
              </>
            )}
          </Button>
        </div>

        {/* Revalidation confirmation dialog */}
        <AlertDialog open={showRevalidateDialog} onOpenChange={setShowRevalidateDialog}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle className="flex items-center gap-2">
                <RefreshCwIcon className="size-5 text-primary" />
                Gerar novos titulos?
              </AlertDialogTitle>
              <AlertDialogDescription>
                Ao gerar novos titulos, as fases seguintes (Descricao e Tags) serao marcadas
                para revalidacao. Os dados existentes serao preservados, mas voce podera
                optar por revalidar quando chegar nessas fases.
                {additionalContext && (
                  <span className="block mt-2 text-foreground">
                    <strong>Sua dica:</strong> {additionalContext}
                  </span>
                )}
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancelar</AlertDialogCancel>
              <AlertDialogAction onClick={handleConfirmRevalidate}>
                <CheckCircleIcon className="size-4 mr-2" />
                Sim, gerar novos
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </div>
  )
}
