'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import {
  ArrowRightIcon,
  CheckCircleIcon,
  RefreshCwIcon,
  AlertTriangleIcon,
  FileTextIcon,
  Loader2Icon,
} from 'lucide-react'

import { log } from '@/lib/logger'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import type { UseWizardReturn } from '@/hooks/use-wizard'
import type { Video } from '@/types/video'
import type { Phase6Response } from '@/lib/llm/types'

import { getNextPhaseNameForType } from '@/lib/wizard'

import { ProcessingSpinner } from '../processing-spinner'

interface Phase6DescriptionProps {
  wizard: UseWizardReturn
  video: Video
  /** Result from LLM processing (null while processing or if error) */
  descriptionResult: Phase6Response | null
  /** Error message if processing failed */
  error?: string | null
  /** Callback to retry processing after error */
  onRetry?: () => void
  /** Callback when revalidation is requested with additional context */
  onRevalidate?: (additionalContext: string) => void
  /** Callback when description is changed (debounced). Returns promise for advance sync. */
  onDescriptionChange?: (description: string) => Promise<void>
  className?: string
}

const MAX_DESCRIPTION_CHARS = 5000
const MAX_ADDITIONAL_CONTEXT_CHARS = 200
const DEBOUNCE_DELAY = 1500

/**
 * Phase 6: Description - Reprocessable (Type 1)
 *
 * Displays SEO-optimized description generated by LLM for user editing.
 *
 * Key features:
 * - Auto-processes on phase entry
 * - Editable textarea with auto-save (debounced)
 * - Additional context input for revalidation
 * - Revalidar button with confirmation dialog
 * - Type 1: Can be reprocessed multiple times
 * - Always saves description before advancing (even if user didn't edit)
 *
 * @see processamento_video.md - Fase 6 - Descricao
 */
export function Phase6Description({
  wizard,
  video,
  descriptionResult,
  error,
  onRetry,
  onRevalidate,
  onDescriptionChange,
  className,
}: Phase6DescriptionProps) {
  const hasResult = descriptionResult !== null
  const hasError = !!error

  // Description state - initialize from result or video.description
  const [description, setDescription] = useState<string>(
    descriptionResult?.description ?? video.description ?? ''
  )

  // Update description when result changes
  useEffect(() => {
    if (descriptionResult?.description) {
      setDescription(descriptionResult.description)
    }
  }, [descriptionResult?.description])

  // Additional context for revalidation
  const [additionalContext, setAdditionalContext] = useState('')

  // State for revalidation confirmation dialog
  const [showRevalidateDialog, setShowRevalidateDialog] = useState(false)

  // State for advancing to next phase (prevents double clicks)
  const [isAdvancing, setIsAdvancing] = useState(false)

  // Debounce timer ref
  const debounceTimerRef = useRef<NodeJS.Timeout | null>(null)

  // Check if can advance: result must exist and description must be non-empty
  const canAdvance = hasResult && description.trim().length > 0 && !hasError && !isAdvancing

  // Handle description change with debounce
  const handleDescriptionChange = useCallback(
    (value: string) => {
      setDescription(value)

      // Clear existing timer
      if (debounceTimerRef.current) {
        clearTimeout(debounceTimerRef.current)
      }

      // Set new debounce timer
      debounceTimerRef.current = setTimeout(() => {
        onDescriptionChange?.(value)
      }, DEBOUNCE_DELAY)
    },
    [onDescriptionChange]
  )

  // Cleanup timer on unmount
  useEffect(() => {
    return () => {
      if (debounceTimerRef.current) {
        clearTimeout(debounceTimerRef.current)
      }
    }
  }, [])

  const handleAdvanceClick = async () => {
    if (!canAdvance) return
    setIsAdvancing(true)
    // Clear any pending debounce timer
    if (debounceTimerRef.current) {
      clearTimeout(debounceTimerRef.current)
    }
    // Always save description before advancing (even if user didn't edit)
    try {
      await onDescriptionChange?.(description)
    } catch (error) {
      // Log error but don't block advance - user can still proceed
      log('WARN', 'Failed to save description on advance, continuing anyway', {
        error: error instanceof Error ? error.message : 'Unknown error',
      })
    }
    wizard.completePhaseAndAdvance(6, { description })
  }

  const handleRevalidateClick = () => {
    setShowRevalidateDialog(true)
  }

  const handleConfirmRevalidate = () => {
    setShowRevalidateDialog(false)
    onRevalidate?.(additionalContext)
  }

  const remainingDescriptionChars = MAX_DESCRIPTION_CHARS - description.length
  const remainingContextChars = MAX_ADDITIONAL_CONTEXT_CHARS - additionalContext.length

  return (
    <div className={className}>
      <div className="space-y-4">
        {/* Error state with retry button */}
        {hasError && (
          <Card className="border-destructive">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-destructive">
                Erro na Geracao de Descricao
              </CardTitle>
              <CardDescription>
                Nao foi possivel gerar a descricao automaticamente.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center justify-center gap-4 py-6">
                <AlertTriangleIcon className="size-12 text-destructive" />
                <p className="text-sm text-muted-foreground text-center">{error}</p>
                {onRetry && (
                  <Button variant="outline" onClick={onRetry}>
                    <RefreshCwIcon className="size-4 mr-2" />
                    Tentar novamente
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Loading state when no result yet */}
        {!descriptionResult && !hasError && (
          <ProcessingSpinner text="Gerando descrição do vídeo..." />
        )}

        {/* Description textarea */}
        {descriptionResult && !hasError && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <FileTextIcon className="size-4" />
                Descricao Gerada
              </CardTitle>
              <CardDescription>
                Edite a descricao conforme necessario. Alteracoes sao salvas automaticamente.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Textarea
                  id="description"
                  value={description}
                  onChange={(e) => handleDescriptionChange(e.target.value)}
                  maxLength={MAX_DESCRIPTION_CHARS}
                  className="min-h-[300px] resize-y font-mono text-sm"
                  placeholder="Descricao do video..."
                />
                <div className="flex justify-end text-xs text-muted-foreground">
                  <span className={remainingDescriptionChars < 500 ? 'text-amber-500' : ''}>
                    {remainingDescriptionChars} caracteres restantes
                  </span>
                </div>
              </div>

              {/* Additional context input for revalidation */}
              <div className="pt-4 border-t">
                <div className="space-y-2">
                  <Label htmlFor="additional-context" className="text-sm font-medium">
                    Dica para nova descricao (opcional)
                  </Label>
                  <Textarea
                    id="additional-context"
                    placeholder="Ex: Foque mais nos beneficios para o publico, mencione o patrocinador..."
                    value={additionalContext}
                    onChange={(e) => setAdditionalContext(e.target.value)}
                    maxLength={MAX_ADDITIONAL_CONTEXT_CHARS}
                    className="min-h-[80px] resize-none"
                  />
                  <div className="flex justify-between items-center text-xs text-muted-foreground">
                    <span>Use para gerar nova descricao com contexto adicional</span>
                    <span className={remainingContextChars < 20 ? 'text-amber-500' : ''}>
                      {remainingContextChars} caracteres restantes
                    </span>
                  </div>
                </div>

                {/* Revalidar button */}
                <div className="mt-3">
                  <Button
                    variant="outline"
                    onClick={handleRevalidateClick}
                    disabled={!onRevalidate}
                  >
                    <RefreshCwIcon className="size-4 mr-2" />
                    Gerar nova descricao
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Advance button */}
        <div className="flex justify-end pt-4">
          <Button onClick={handleAdvanceClick} disabled={!canAdvance}>
            {isAdvancing ? (
              <>
                Avançando...
                <Loader2Icon className="size-4 ml-2 animate-spin" />
              </>
            ) : (
              <>
                Avançar para {getNextPhaseNameForType(6, video.videoType)}
                <ArrowRightIcon className="size-4 ml-2" />
              </>
            )}
          </Button>
        </div>

        {/* Revalidation confirmation dialog */}
        <AlertDialog open={showRevalidateDialog} onOpenChange={setShowRevalidateDialog}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle className="flex items-center gap-2">
                <RefreshCwIcon className="size-5 text-primary" />
                Gerar nova descricao?
              </AlertDialogTitle>
              <AlertDialogDescription>
                Ao gerar nova descricao, a fase seguinte (Tags) sera marcada para revalidacao.
                Os dados existentes serao preservados, mas voce podera optar por revalidar
                quando chegar nessa fase.
                {additionalContext && (
                  <span className="block mt-2 text-foreground">
                    <strong>Sua dica:</strong> {additionalContext}
                  </span>
                )}
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancelar</AlertDialogCancel>
              <AlertDialogAction onClick={handleConfirmRevalidate}>
                <CheckCircleIcon className="size-4 mr-2" />
                Sim, gerar nova
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </div>
  )
}
