'use client'

import { ImageIcon } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import type { Video } from '@/types/video'

interface PhaseThumbnailProps {
  video: Video
  /** Callback when "Continuar para Publicar" is clicked. Disabled until a thumbnail is selected. */
  onAdvance?: () => void
  /**
   * URL of the currently selected thumbnail (either generated by the LLM or uploaded
   * manually by the producer). Undefined while nothing has been selected yet.
   *
   * Story 22.3a delivers the skeleton only — selection is wired in Stories 22.3b–22.3g.
   */
  selectedThumbnailUrl?: string
  className?: string
}

/**
 * Phase Thumbnail — Epic 22 / Story 22.3 (broken into sub-stories 22.3a..22.3g).
 *
 * This sub-story (22.3a) delivers the skeleton + breadcrumb integration. The
 * producer sees a placeholder while the actual flow (generation + manual upload
 * + history + guest crop + persistence) lands in 22.3b through 22.3g.
 *
 * The phase is gated by `podcast.features.thumbnailGeneration` and only renders
 * for `episode` and `cut` video types — see `getPhasesForVideoTypeWithFeatures`
 * in `src/lib/wizard/constants.ts`.
 *
 * Position in the wizard: between Tags (phase 7) and Publicar (phase 8).
 */
export function PhaseThumbnail({ video, onAdvance, selectedThumbnailUrl, className }: PhaseThumbnailProps) {
  const canAdvance = Boolean(selectedThumbnailUrl)

  return (
    <div className={className} data-testid="phase-thumbnail" data-video-id={video.id}>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon className="h-5 w-5" />
            Thumbnail
          </CardTitle>
          <CardDescription>
            Gere o thumbnail do vídeo via IAra ou faça upload de uma imagem própria. A
            thumbnail selecionada é enviada ao YouTube na próxima fase.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/*
            Story 22.3a delivers the skeleton only. The interactive surface
            (dual path: gerar via IAra / upload manual, preview Base/Referência,
            histórico de versões, crop da foto do convidado, seleção, persistência)
            lands in Stories 22.3b through 22.3g — see
            _bmad-output/implementation-artifacts/epic-22-thumbnails.md.
          */}
          <div className="rounded-md border border-dashed bg-muted/30 p-6 text-sm text-muted-foreground">
            <p className="font-medium text-foreground">Fase em construção</p>
            <p className="mt-2">
              A interface completa (gerar via IAra, upload manual, histórico de versões e
              seleção) está sendo entregue incrementalmente nas sub-stories 22.3b–22.3g.
            </p>
          </div>

          <div className="flex justify-end">
            <Button onClick={onAdvance} disabled={!canAdvance}>
              Continuar para Publicar
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
