/**
 * GET /midiakit.pdf — serves the always-fresh mediakit generated by the
 * `mediakit-generator` job (Epic 30 da IAra).
 *
 * The /midiakit page's download button has pointed at this path since ever —
 * it used to 404 (no PDF was ever committed to public/). This route keeps the
 * stable URL and streams the GCS object the generator overwrites daily
 * (write-through with failsafe: a broken render never replaces the last good
 * PDF, so whatever is here is always a verified kit).
 *
 * Cache: the object changes daily behind a STABLE url — short max-age so a
 * sponsor never keeps yesterday's numbers for long (retro-22 AI 10).
 */
import { Storage } from "@google-cloud/storage";

export const dynamic = "force-dynamic";

const MEDIAKIT_OBJECT_PATH = "media-kit/latest.pdf";
const DOWNLOAD_FILENAME = "Midiakit-PPT-Nao-Compila.pdf";

let storageClient: Storage | undefined;

function getBucketName(): string {
  return process.env.MEDIAKIT_BUCKET || "";
}

function getStorage(): Storage {
  if (!storageClient) {
    storageClient = new Storage({
      projectId: process.env.GOOGLE_PROJECT_ID || "pptnc-stage",
      // ADC handles credentials (Cloud Run SA in prod, gcloud locally).
    });
  }
  return storageClient;
}

export async function GET(): Promise<Response> {
  const bucketName = getBucketName();
  if (!bucketName) {
    console.error("[midiakit.pdf] MEDIAKIT_BUCKET not configured");
    return new Response("Midiakit indisponível no momento.", { status: 503 });
  }

  try {
    const [pdf] = await getStorage()
      .bucket(bucketName)
      .file(MEDIAKIT_OBJECT_PATH)
      .download();

    return new Response(new Uint8Array(pdf), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${DOWNLOAD_FILENAME}"`,
        "Content-Length": String(pdf.length),
        "Cache-Control": "public, max-age=300",
      },
    });
  } catch (error) {
    const code = (error as { code?: number }).code;
    if (code === 404) {
      console.error("[midiakit.pdf] object not found in bucket", { bucketName });
      return new Response("Midiakit ainda não publicado.", { status: 404 });
    }
    console.error("[midiakit.pdf] download failed", {
      error: error instanceof Error ? error.message : error,
    });
    return new Response("Midiakit indisponível no momento.", { status: 503 });
  }
}
