/**
 * API route for video tags operations.
 *
 * PUT: Update the video tags (edited by user or generated by AI)
 *
 * Tags are stored flat on the video document at root level as Array<string>.
 *
 * @see processamento_video.md - Fase 7 - Tags
 */

import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

import { auth } from '@/lib/auth'
import { getVideoAdmin, updateVideoAdmin } from '@/lib/firebase/videos-admin'
import { PODCAST_ID } from '@/lib/firebase/config'
import { log } from '@/lib/logger'
import {
  authExpiredResponse,
  notFoundResponse,
  handleVideoFieldError,
} from '@/lib/api/video-field-handler'

/**
 * Schema for validating tags update request body.
 * YouTube limit: 500 characters total for all tags combined.
 */
const TagsUpdateSchema = z.object({
  tags: z
    .array(z.string().min(1).max(100))
    .max(30, 'Maximo de 30 tags')
    .refine(
      (tags) => tags.join(',').length <= 500,
      'Total de caracteres das tags excede 500'
    ),
})

export const runtime = 'nodejs' // REQUIRED for firebase-admin

interface RouteContext {
  params: Promise<{ videoId: string }>
}

/**
 * PUT /api/videos/[videoId]/tags
 *
 * Updates the tags for a video.
 * Used when user edits the AI-generated tags in Phase 7.
 */
export async function PUT(
  request: NextRequest,
  context: RouteContext
): Promise<NextResponse> {
  const session = await auth()
  if (!session) {
    return authExpiredResponse()
  }

  const { videoId } = await context.params

  try {
    const body = await request.json()

    // Validate tags with Zod BEFORE persisting
    const { tags } = TagsUpdateSchema.parse(body)

    // Check video exists
    const video = await getVideoAdmin(PODCAST_ID, videoId)
    if (!video) {
      return notFoundResponse('Video')
    }

    // Update video with new tags
    await updateVideoAdmin(PODCAST_ID, videoId, { tags })

    log('INFO', 'Video tags updated', {
      videoId,
      tagCount: tags.length,
      totalChars: tags.join(',').length,
    })

    return NextResponse.json({
      data: {
        videoId,
        tagCount: tags.length,
      },
    })
  } catch (error) {
    return handleVideoFieldError(error, 'tags', videoId)
  }
}
